### ISSUE TITLE
regression: with pipefail, false | true doesn't trip errexit

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#121]
From https://unix.stackexchange.com/questions/580739/set-eo-pipefail-differs-on-ksh-and-bash

```
$ ksh93 -o errexit -o pipefail -c '(exit 3) | true; echo "still here despite $? status"'
still here despite 3 status
```

(expected no output)

Looks like a regression introduced by ksh93u+. ksh93u worked as expected in that regard.

**Comment by McDutchie** [comment]
ksh2020 has this bug too, and presumably so does 93v-.

**Comment by McDutchie** [comment]
So, this block in `sh_exec()` handles `-o pipefail` by setting up the state to record multiple exit statuses:
https://github.com/ksh93/ksh/blob/bd283959be69cb6824381cdafbdc9273c69bc881/src/cmd/ksh93/sh/xec.c#L1918-L1927
And this bit near the end of `sh_exec()` determines whether to check traps, including the `ERR` trap (and as far as ksh93 is concerned, `-o errexit` is just another variant of the ERR trap):
https://github.com/ksh93/ksh/blob/bd283959be69cb6824381cdafbdc9273c69bc881/src/cmd/ksh93/sh/xec.c#L2647-L2649
The problem is that `sh_chktrap()` is not getting called when it should. By inserting a debug warning reporting the values of the variables, I have determined that the `sh_exec()` run that produces the correct 3 exit status (`shp->exitval==3`) in Stéphane's reproducer, but it has the `echeck` flag at zero.

So an obvious fix is to insert an `echeck = 1;` assignment on line 1926. And sure enough, that seem to work. The reproducer now produces exit status 3 and no output, as expected.

However, that fix produces one regression test failure:
```
	basic.sh[528]: trap on ERR not getting triggered
```
The test in question is:
https://github.com/ksh93/ksh/blob/bd283959be69cb6824381cdafbdc9273c69bc881/src/cmd/ksh93/tests/basic.sh#L527-L528

**Comment by McDutchie** [comment]
And it turns out that the test failure message lies. If we execute the test manually (it is run with `pipefail` active, which was set earlier in the script), it turns out the ERR trap is in fact triggered… twice:
```
$ arch/*/bin/ksh -o pipefail -c '{ trap '\''print trap'\'' ERR; print -n | $(whence -p false); } & wait $!'
trap
trap
```
If we execute it without pipefail, it's only triggered once:
```
$ arch/*/bin/ksh -c '{ trap '\''print trap'\'' ERR; print -n | $(whence -p false); } & wait $!'            
trap
```

**Comment by McDutchie** [comment]
So why is it getting triggered twice? Because `sh_exec()` is run once for the pipeline as a whole, and then another time for each element in it. And there is already code that sets the `echeck` flag for the right-hand side of the pipe (which is handled as part of `case TSETIO` as it does not fork): https://github.com/ksh93/ksh/blob/bd283959be69cb6824381cdafbdc9273c69bc881/src/cmd/ksh93/sh/xec.c#L1836-L1840
So the trap gets triggered once for the right hand side of the pipe (whether or not `pipefail` is active) and once for `pipefail` (if it is active). To fix this bug properly, I think the `echeck = 1` above needs to only be done if `pipefail` is *not* active, `if(!sh_isoption(SH_PIPEFAIL))`.

**Comment by McDutchie** [comment]
A simpler way to fix it appears to be move the `echeck = 1;` from line 1838 (which is in the `TSETIO` case) to somewhere in the `TFIL` case, but keep it unconditional and not subject to `SH_PIPEFAIL`. That seems to do the right thing as well; all tests pass.
