### ISSUE TITLE
Add -T (-o functrace) option as in bash

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#162]
Discussion: https://github.com/ksh93/ksh/issues/155#issuecomment-766305476

Some scripts may rely on the bug that caused the `DEBUG` trap to be incorrectly inherited by subshells and ksh functions (contrary to the documentation). The bug and the associated crashes/data corruption have been fixed (see commits linked in #155), but there should probably be a shell option for subshells and ksh functions to inherit the `DEBUG` trap. Bash has such an option so we should probably use the same name/letter.

**Comment by McDutchie** [comment]
The `-T` short-form option name has a completely different meaning on mksh, and it existed on ksh 93u+ as an unused internal debug option (which I removed in 63c55ad71bda27e5f1a33b4f1e9e1e3da12419b0). So, to minimise confusion, I think it's best that we only implement the long `--functrace`/`-o functrace` name on ksh 93u+m.

Moreover, the ksh behaviour is not going to be exactly the same as on bash. On bash, the `DEBUG` trap value itself is never locally scoped; changes made to it in functions propagate upwards to the parent scope. This is not the case on ksh, where all traps are local to ksh-style functions.

Shell options are also not local to functions on bash, and -x/--xtrace is not locally disabled within function calls. On ksh, it needs to be explicitly re-enabled within a function if you want to trace the function body.

So I think it would make sense for a ksh --functrace option to cause functions to inherit the xtrace status as well as the DEBUG trap. After all, they are triggered under identical conditions in every other way; they are essentially the same thing, handled differently.

I've been working on the implementation, which is simpler than I expected.

**Comment by McDutchie** [comment]
But of course, handling this for ksh functions is not enough. Traps are also reset in subshells and the bash functrace option makes subshells inherit the DEBUG trap. We should do the same. See https://github.com/ksh93/ksh/issues/155#issuecomment-766293947

**Comment by McDutchie** [comment]
Ping @ko1nksm – I think this new `--functrace` option might make you happy. :)  Would you mind testing it?

**Comment by ko1nksm** [comment]
Wow! I thought the implementation of this would take more time. Thanks for the great work!

I incorporated this and measured the coverage of the shellspec itself.

- ksh Version AJM 93u+ 2012-08-01
  - Code covered: 66.18%, Executed lines: 3330, Instrumented lines: 5032
- ksh Version AJM 93u+m/1.0.0-beta.2 2022-06-04 (without `set -o functrace`)
  - Code covered: 59.88%, Executed lines: 3013, Instrumented lines: 5032
- ksh Version AJM 93u+m/1.0.0-beta.2 2022-06-04 (with `set -o functrace`)
  - Code covered: 64.45%, Executed lines: 3243, Instrumented lines: 5032

FYI: Since bash and ksh have different code paths, they cannot be directly compared. shellspec coverage is about this much from the beginning.

- bash 4.4.20(1)-release
  - Code covered: 65.74%, Executed lines: 3308, Instrumented lines: 5032
- bash 5.0.11(1)-release
  - Code covered: 66.36%, Executed lines: 3339, Instrumented lines: 5032

Coverage was greatly reduced by the  earlier fixes  `(66.18% -> 59.88%)`, but appears to have recovered enough to be considered adequate `(59.88% -> 64.45%)`. There appear to be `3330 - 3243 = 87` unmeasured lines of code. The reason for the slight decrease compared to 93u+ is still unclear. It is possible that this is the result of a defect that has been corrected and the measurement is now better and more accurate. I would look into it a little more closely.

**Comment by McDutchie** [comment]
@ko1nksm:
> There appear to be `3330 - 3243 = 87` unmeasured lines of code. The reason for the slight decrease compared to 93u+ is still unclear. It is possible that this is the result of a defect that has been corrected and the measurement is now better and more accurate. I would look into it a little more closely.

If you're using $LINENO in those calculations, you should know that ksh 93u+ has few bugs with LINENO that we fixed. See: d89ef0fafafd9667d38a91ce6d282a661d762bde, 2c22ace1e6200e341c6dc018c92a2021bcb06ec2, f056472f368f42883c7f80c977598b90140d5c77, 0e0ad6c7005aa33123fd0fb1ced4ec507507318d
