### ISSUE TITLE
Split out libast as a git submodule?

### ISSUE THREAD

**Issue by lkujaw** [ksh93/ksh#185]
This is more of a wish list item than a bug, but it would be nice if libast could become a separate component for a future project to get nmake or other ast utilities working. My experience is that there are very few contemporary build tools (recent autotools are quite broken) available these days that support uncommon platforms like SVR4 well. The only viable alternative I know of is a combination of imake and iffe that I created as part of the CDE project. If the Mamfile situation ever becomes untenable, I'd be happy to help make adaptations.

**Comment by McDutchie** [comment]
This repo removed nmake at the beginning because it simply doesn't work with clang and has lots of problems when using gcc. I've abandoned the experimental nmake branch in this repo because it never worked right, plus the build takes twice as long. nmake is also both abandoned and very complex, plus (given the general quality standards evident in the ksh source code) likely to be as buggy as the original AT&T ksh is.

nmake is also designed for the entire 1990s AT&T ecosystem and doesn't work that well outside of it. It's dependent on and interwined with 3DFS (a very, very dead userspace versioning file system with serious race conditions) and libcoshell (an equally disused shell-based ksh-specific network distribution facility). Nobody cares about these now as there are much better alternatives that don't depend on any shell in particular, so they are basically pure bit rot at this point. I removed that baggage from this repo a while ago and I've no intention of reintroducing it.

Maintaining ksh is already an obsession to the point that my partner is questioning it and my kids see less of me than they should. I can't afford to add more complication to my life.

If someone else maintains a libast repo, incorporating all the ksh 93u+m fixes into it, then I may use it, as that would actually reduce my workload. But it needs to be made to fit with the way I work here.

If you want to do that, and reintroduce nmake (good luck with that beast!), your best bet for that is probably to re-fork the ast repository and start from there. This repo has now made so many customisations without nmake that it's diverged too much and reintroducing nmake would not be practical. However, most of those are in src/cmd/ksh93 and src/cmd/INIT. Nothing much has really changed about the directory or dependency tree in libast (except the #include you recently added). So it would probably not be too hard to backport all the changes in libast to a newly forked ast repo.

**Comment by McDutchie** [comment]
Re: the Mamfile situation, that became a lot more tolerable after I added [support for indentation](https://github.com/ksh93/ksh/blob/72968eaed61064d298ebeb683dab0819fa4d0f47/src/cmd/INIT/mamake.c#L1133-L1136) which was trivial, made a little [script to auto-indent the Mamfiles](https://github.com/ksh93/ksh/blob/72968eaed61064d298ebeb683dab0819fa4d0f47/bin/Mamfile_indent) which was nearly as trivial, and found [the original documentation for the language](http://web.archive.org/web/20041227143022/http://www2.research.att.com/~gsf/mam/mam.html). mamake is also small and simple (a single .c file!) so while I don't understand everything yet, it is certainly within the realm of feasibility to learn to understand properly. nmake, not so much.

**Comment by lkujaw** [comment]
I completely understand where you are coming from about needing to keep complexity to a minimum in this project. While it's fun to unravel Korn's puzzle-like code, I have experience with it becoming a bit of a time sink :-). I've been using the AST tools on UnixWare for a while now because they are surprisingly feature-rich compared to their SVR4 counterparts, so it might make sense to publish updates on GitHub, for folks looking for what AT&T probably would've done had they not split USL off.

Anyway, thank you for the very detailed explanation, and I will go ahead and close this and let you know when/if I get a separate repo set up for libast so that we can hopefully reduce duplication.

**Comment by McDutchie** [comment]
> Korn's puzzle-like code

If only it were as consistent as a puzzle, ksh would not have been so buggy... Too much of it is just wrong and/or broken. But I'm going to resist going off on another rant here :)
