### ISSUE TITLE
eval: syntax error: `((' unexpected

### ISSUE THREAD

**Issue by DesantBucie** [ksh93/ksh#196]
Hi, i've got an error (eval: syntax error: `((' unexpected ) on u+m (but working), while working fine on u+ 2012. Now i'm not sure is it my fault or bug.
u+m is yesterday compilation.
```
integer i=0
for .. in ..
...
((i++))#error
``` 
What is more funny, if i redirect error to /dev/null it doesn't show error on u+m but stops working on u+ 2012:
((i++)) 2> /dev/null

**Comment by DesantBucie** [comment]
Stupid me, spaces in front and back are needed ...
`(( i++ ))`

**Comment by McDutchie** [comment]
Spaces are **not** needed for regular round parentheses, ever. That includes arithmetic expansion and arithmetic commands.

That's because parentheses are fundamental lexical tokens in the parser, like `;`, `<` or `>`, which do not need spaces either. This is different from `{`, `}`, `[[`, and `]]`. They are parsed like a reserved word like `if` or `case`, so they need spaces. It is also different from `[`, which is parsed like a regular command name like `print` or `ls`, so needs spaces too.

Unfortunately you provided way too little code and context for me to have a chance of actually figuring out the cause of your problem. But it is definitely not what you think it is.

**Comment by DesantBucie** [comment]
The problem was here, it's basically a cut out function from [here](https://github.com/l0stman/kshrc), that sets colors to array. 

```
case $(uname) in
    FreeBSD)
        cap_setfg=AF
        cap_setbg=AB
        ;;
    *)
        cap_setfg=setaf
        cap_setbg=setab
        ;;
esac
load_colors()
{
    typeset -A fg bg
    typeset color
    integer i=0

    for color in black red green brown blue magenta cyan white 
    do
        fg+=([$color]=$(tput $cap_setfg $i $i $i))
        bg+=([$color]=$(tput $cap_setbg $i $i $i))
        ((i++))
        #why throws error?
    done
    fg+=([reset]=$(tput $cap_setfg 7 7 7))
    bg+=([reset]=$(tput $cap_setbg 0 0 0))
}
load_colors
```

When there were no spaces u+m would:
`/Users/dsnt/.kshrc[25]: .[64]: eval: syntax error: '((' unexpected ` (x7),
while u+ has no problems.
When i added spaces: (( i++ )) both seems to work fine.

**Comment by McDutchie** [comment]
Thanks for linking to the full script. That should not be throwing a syntax error. I'm going to investigate.

**Comment by McDutchie** [comment]
I cannot reproduce the syntax error if I run the bit of the script you included above. When I add this at the bottom
```sh
print "${.sh.version}"
for index in "${!fg[@]}"
do
        printf 'fg[%q]: %q\n' "$index" "${fg[$index]}"
done
for index in "${!bg[@]}"
do
        printf 'bg[%q]: %q\n' "$index" "${bg[$index]}"
done
```
the output is entirely as expected:
```
Version AJM 93u+m/1.0.0-alpha+ef8b80cf 2021-02-26
fg[black]: $'\E[30m'
fg[blue]: $'\E[34m'
fg[brown]: $'\E[33m'
fg[cyan]: $'\E[36m'
fg[green]: $'\E[32m'
fg[magenta]: $'\E[35m'
fg[red]: $'\E[31m'
fg[reset]: $'\E[37m'
fg[white]: $'\E[37m'
bg[black]: $'\E[40m'
bg[blue]: $'\E[44m'
bg[brown]: $'\E[43m'
bg[cyan]: $'\E[46m'
bg[green]: $'\E[42m'
bg[magenta]: $'\E[45m'
bg[red]: $'\E[41m'
bg[reset]: $'\E[40m'
bg[white]: $'\E[47m'
```
I will try to install that full prompt package on a Linux system to see what happens. Something strange is going on. Why is the syntax error claiming to be from an `eval` command? Why do you get seven syntax errors though that loop goes through eight iterations?

**Comment by McDutchie** [comment]
I have installed that full kshrc package on a Debian Linux system now. I'm running it on that same 93u+m version. It seems to be working as expected. No syntax errors.

(Oh, except when I run `mcd` and then Ctrl+C out of that, everything crashes into an infinite loop. But the same thing happens on 93u+.)

Did you change anything in that code?

**Comment by DesantBucie** [comment]
Yes, i only copied a small amount of code, that is responsible for aliasing `tput setaf` to array, so prompts, are compatible cross-platform. Sorry for not being precise.

If you want to try to reproduce, you can clone my repo korny as this is where problem occurs. The file responsible for coloring is in prompts/color_prompt.ksh
And please remove `2> /dev/null` after `((i++))`.

Or you can wait, and i'll prepare special branch, but I'm out right now.

**Comment by DesantBucie** [comment]
All right, branch if you would installed it, then you just need to enter ~/.korny and git switch dev and git pull origin dev.

**Comment by McDutchie** [comment]
I've installed your korny repo, and removed the `2>/dev/null` after the `((i++))` in `load_colors()` in `colors_prompt.ksh`. Now I can reproduce the problem.

Clues appear when we invoke ksh with `-x`... this is from the lastest 93u+m:
```
[stuff skipped]
+ trap 'eval "_do_autocd ${.sh.command}"' DEBUG
+ eval '_do_autocd for PLUG in /home/i/inlv/.korny/plugs/colors_prompt.ksh'
+ _do_autocd for PLUG in /home/i/inlv/.korny/plugs/colors_prompt.ksh
```
Well, it looks like [autocd](https://github.com/ksh93/ksh/issues/187#issuecomment-782729100) is starting to interfere with your scripts here.

So, why does this not occur in ksh 93u+? Because, ironically, the `DEBUG` trap on 93u+ is so broken it won't really run autocd properly at all!

```
[more stuff skipped]
+ eval '_do_autocd (( i++ ))'
/home/i/inlv/.kshrc[27]: .[66]: eval: syntax error: `((' unexpected
```
Annnd there is the cause of your syntax error. Of course if you prefix `_do_autocd`, or any word `foo`, to an unquoted `((i++))`, that is a straightforward syntax error:
```
$ _do_autocd ((i++))
ksh: syntax error: `((' unexpected
```

So, the bug is probably in autocd, not in ksh. When you load autocd on an interactive shell, and turn on `set -x`:
```
$ . ./autocd.ksh
$ set -x
$ ((i++))
+ eval '_do_autocd (( i++ ))'
ksh: eval: syntax error: `((' unexpected
+ ((i++))
$ (( i++ ))
+ eval '_do_autocd ((  i++  ))'
ksh: eval: syntax error: `((' unexpected
+ (( i++ ))
```

On the other hand... the `DEBUG` trap action is: `eval "_do_autocd ${.sh.command}"`. I expected `${.sh.command}` to be properly shell-quoted to be safe for `eval`. Apparently that is true for regular commands, but not for arithmetic commands. Eeesh.

Let's try this...
```
$ trap 'print -r ".sh.command is: ${.sh.command}"' DEBUG
$ 'one two' "three four"                                
.sh.command is: 'one two' 'three four'    <== properly re-quoted
ksh: one two: not found
$ ((i++))
.sh.command is: (( i++ ))                 <== NOT quoted! Will cause syntax error when eval'ed as "foo (( i++ ))"
```
That explains the syntax errors you're getting.

Your solution, for now: remove autocd. It needs rethinking. At this point I'm undecided whether the bug is in ksh or in autocd.

**Comment by DesantBucie** [comment]
All right, i'll rethink autocd too, thanks for your time.

**Comment by DesantBucie** [comment]
I've tested zsh and autocd there, doesn't autodetect directories names with spaces as well, but if you press tab to autocomplete, it will automatically print a space for you, I think this one, works exactly like zsh's `setopt autocd`
```
_do_autocd()
{
        if      ! command -v "$1" >/dev/null && [[ -d $1 ]]
        then    CDPATH= command cd -- "$1"
                return 2
        fi
}
trap '_do_autocd "${.sh.command}"' DEBUG
```
<img width="400" alt="Screenshot 2021-02-26 at 23 29 43" src="https://user-images.githubusercontent.com/46130107/109362103-a391e680-788a-11eb-9be6-58eafe29b1ba.png">
<img width="429" alt="Screenshot 2021-02-26 at 23 33 00" src="https://user-images.githubusercontent.com/46130107/109362282-fbc8e880-788a-11eb-9581-23d875b0b7d8.png">

Sorry, for such a mess I have made I don't want to piss you with this function that purpose is only so i can save 2ms not writing `cd`. If you think it's fine, I can post it, on old thread.

**Comment by McDutchie** [comment]
Are you sure you were executing that version when you had it working with a directory with spaces? Because I think that's impossible, as that gets shellquoted, and you're no longer removing the quotes with 'eval'. With that version, I get:
```
$ /Library/Application\ Support
ksh: /Library/Application Support: cannot execute [Is a directory]
```
And there is another problem with it:
```
$ i=1
$ mkdir "(( i++ ))"
$ ((i++))
$ pwd
/usr/local/src/ksh93/ksh/(( i++ ))
```
So, I don't think this one works properly.

**Comment by McDutchie** [comment]
Try this. This version of the trap action assumes that `${.sh.command}` will contain either properly shellquoted command arguments, or an arithmetic command starting with `((` (but it's enough to check for the initial `(` as that alone would be a syntax error to eval after a prefix word). It also refuses to eval or run the function if the shell is not interactive, or if we're currently executing a function (if `${.sh.level}` is nonzero).

This does actually work on ksh 93u+, but not if you define a complicated prompt (such as your own) that executes command substitutions, as that kills the `DEBUG` trap on 93u+ due to one of the many bugs with that. Those bugs have been fixed on 93u+m.

```sh
_do_autocd()
{
        if      (($#==1)) && ! command -v "$1" >/dev/null && [[ -d $1 ]]
        then    printf 'cd -- %q\n' "$1" >&2
                CDPATH= command cd -- "$1"
                return 2
        fi
}
trap '((!.sh.level)) && [[ $1 != \(* && -o interactive ]] && eval "_do_autocd ${.sh.command}"' DEBUG
```
*edit:* Silly mistake: `$1 != \(*` should be `${.sh.command} != \(*`.

**Comment by McDutchie** [comment]
Relevant bugfix, just applied: https://github.com/ksh93/ksh/commit/c928046aa9abfe4287acad5d6abb8fbed4c75096

Before this fix, it was not possible to use `${.sh.fun}` to check if you're executing a function if you're executing `DEBUG` traps. Thankfully `${.sh.level}` did work.

**Comment by DesantBucie** [comment]
Ok thanks

EDIT: I did made some kind of mistake sending you that, but i don't know what.

**Comment by McDutchie** [comment]
There was another silly mistake in the last version, here's a corrected one. @DesantBucie @posguy99
```sh
_do_autocd()
{
        if      (($#==1)) && ! command -v "$1" >/dev/null && [[ -d $1 ]]
        then    printf 'cd -- %q\n' "$1" >&2
                CDPATH= command cd -- "$1"
                return 2
        fi
}
trap '((!.sh.level)) && [[ ${.sh.command} != \(* && -o interactive ]] && eval "_do_autocd ${.sh.command}"' DEBUG
```

**Comment by DesantBucie** [comment]
Thanks!
