### ISSUE TITLE
local not found on OpenBSD

### ISSUE THREAD

**Issue by DesantBucie** [ksh93/ksh#197]
Hi, I don't know if u+m was supposed to work on OpenBSD (because of pdksh already built in), but this is error I get every time I use `cd`. This error was present ealier, but thanks to my OpenBSD crash I forgot to put it here.

```
ssh@root:~ => cd /home
-ksh: wcd[93]: _ignore[89]: local: not found [No such file or directory]
```

**Comment by McDutchie** [comment]
The cause is that ksh93 loads `/etc/ksh.kshrc` which is pre-installed on OpenBSD, but programmed for its system shell which is pdksh, the public domain ksh88 clone that was developed independently from AT&T ksh. pdksh has the `local` command. ksh93 does not, or at least not yet. It's on the to-do list. See #123.

You can fix it by changing once instance of `local` to `typeset` in `/etc/ksh.kshrc` on your system. `typeset` creates local variables on both shells, as long as the function is defined with the `function` keyword. I think the rest should work on ksh93 as is.

Scoping also works differently (static on ksh93, dynamic on pdksh -- see Q28 in [this FAQ](http://www.kornshell.com/doc/faq.html)) but that does not matter in this instance.

**Comment by DesantBucie** [comment]
Thanks, works fine now.
