### ISSUE TITLE
Emacs mode: 'value' of arrows is printed instead of moving cursor

### ISSUE THREAD

**Issue by DesantBucie** [ksh93/ksh#224]
Let's assume we have two duplicate folders, 
`alfa`
`alfa (1)`

We want to enter `alfa (1)` so `cd alfa\  \(1\)`, but let's say we missed one right slash. We want to get back and insert it, but instead of moving, cursor, ksh prints `cd alfa\ \(1)^[[D`. The problem only occurs, when backslash is before parenthesis: `\(` or `\)`.

![image](https://user-images.githubusercontent.com/46130107/111076993-0fad5500-84ef-11eb-89bf-d713b411dd74.png)

**Comment by JohnoKing** [comment]
This is intentional behavior that is documented in the man page:
```
       \         If the backslashctrl shell option is on (which is the default
                 setting), this escapes the next character.   Editing  charac‐
                 ters,  the  user's  erase,  kill  and interrupt (normally ^C)
                 characters may be entered in a command line or  in  a  search
                 string  if  preceded  by a \.  The \ removes the next charac‐
                 ter's editing features (if any).  See also lnext which is not
                 subject to any shell option.
```
`set --nobackslashctrl` turns this (mis)feature off.

**Comment by McDutchie** [comment]
See also: 24598fed7c365133c463e7781faee547c0b2bf46

This makes me wonder if I should turn `backslashctrl` off by default, even if it is behaviour that has been documented since times immemorial. Most users don't expect this.

**Comment by hyenias** [comment]
It took me too long to compose the following and you all answered. But since I took the time to compose a nice response, here it is anyways.

There is a new set option in ksh93u+m which allows you to turn off backslash-control-escaping which is on by default. In emacs editing mode, when you key in a `\`  aka backslash, ksh allows you to follow with potential non-printable character(s) in order to be able insert it into the command line string, e.g. `\+CTRL+L` for form feed (FF is ASCII-12).

As you noted on your screen, those control/escape sequences are being inputted into the editing line instead of being sent to the terminal window for cursor movement. Try turning off ksh's backslash-control-escaping via one of the following methods if you normally do not need to directly input control sequences interactively via the editing line:

**Turn Off Backslash-Control-Escaping**
```
$ set +o backslashctrl
or
$ set --nobackslashctrl
```
**How to examine your settings**
```
$ set --state
```
**Turn On Backslash-Control-Escaping**
```
$ set -o backslashctrl
or
$ set --backslashctrl
```
**Putting it all together**
```
$ set --state
set --default --bgnice --braceexpand --emacs --monitor --multiline --viraw
$ set --nobackslashctrl
$ set --state
set --default --nobackslashctrl --bgnice --braceexpand --emacs --monitor --multiline --viraw
$ set --backslashctrl
$ set --state
set --default --bgnice --braceexpand --emacs --monitor --multiline --viraw
```
P.S.:
I am an emacs user and I prefer to have my arrow keys work by default. Nowadays, I doubt the majority of emac users need to insert control sequences using the line editor.

**Comment by DesantBucie** [comment]
Ah, thank you all, now it makes sense.
