### ISSUE TITLE
Alias to `in' causes syntax error

### ISSUE THREAD

**Issue by oguz-ismail** [ksh93/ksh#235]
```
$ alias C='case ' W='x ' I='in '
$ C W I esac
ksh: syntax error: `I' unexpected
$ 
$ alias F='for '
$ F W I ; do : ; done
$
```
This works fine on bosh, ash derivatives, mksh, oksh, and yash. And if I'm not missing anything, tha standard doesn't make an exception for `in`.

**Comment by McDutchie** [comment]
I think ksh is acting correctly according to [the standard](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03_01), which says:

> After a token has been delimited, but before applying the grammatical rules in Shell Grammar, a resulting word that is identified to be the command name word of a simple command shall be examined to determine whether it is an unquoted, valid alias name. However, reserved words in correct grammatical context shall not be candidates for alias substitution.

That `in` cannot possibly the command name of a simple command, because it is not the first word on the command line. So it is not specified to be a candidate for alias substitution. It is also "a reserved word in correct grammatical context" which is another reason aliases should not work there.

**Comment by oguz-ismail** [comment]
> That `in` cannot possibly the command name of a simple command, because it is not the first word on the command line. So it is not specified to be a candidate for alias substitution. It is also "a reserved word in correct grammatical context" which is another reason aliases should not work there.

Both `C` and `W` end with a white space, making the word following them subject to alias substitution; `C` is substituted with `case`, `W` is substituted with `x`, and `I` is supposed to be substituted with `in`, resulting in `case x in esac`. Neither `C`, `W`, or `I` is a reserved word, and there's no point in checking the grammar before alias substitution is complete (and that quote definitely doesn't allow that).

**Comment by McDutchie** [comment]
I see your point about the aliases ending in whitespace. But I think the standard is very unclear.  I'll note that it doesn't work on zsh, either.

Note that in the next version of the standard, any alias whose value is not a simple command (or contains an assignment or redirection) will produce unspecified behaviour. See: https://www.austingroupbugs.net/view.php?id=953#c4214 (scroll up for preceding discussion).

So, with the current standard being unclear and the next version of the standard very probably making this explicitly unspecified, I don't think standards compliance is relevant.

That is no reason not to fix this in and of itself, but I'd like to see an actual use case that breaks because of this. If no use case can be demonstrated, I'm reluctant to touch this.

**Comment by McDutchie** [comment]
Removing the check for `lp->lex.incase` from alias substitution makes it work:
```diff
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -1502,7 +1502,7 @@ breakloop:
 		{
 			/* check for aliases */
 			Namval_t* np;
-			if(!lp->lex.incase && !assignment && fcpeek(0)!=LPAREN &&
+			if(!assignment && fcpeek(0)!=LPAREN &&
 				(np=nv_search(state,shp->alias_tree,HASH_SCOPE))
 				&& !nv_isattr(np,NV_NOEXPAND)
 #if KSHELL
```
But that introduces a much worse bug:
```
$ arch/*/bin/ksh -c 'alias foo=bar; eval "case bar in foo) echo whoops;; esac"'
whoops
```

**Comment by McDutchie** [comment]
Hmm. It looks like that `lp->lex.incase` flag has a special value of 2 that only applies immediately after `case`, before it starts parsing the first glob pattern: https://github.com/ksh93/ksh/blob/3abbb0dcb5a527fa22f40d31d0ed5737d4dda101/src/cmd/ksh93/sh/lex.c#L75

That condition can be whitelisted for alias substitution:
```diff
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -1502,7 +1502,7 @@ breakloop:
 		{
 			/* check for aliases */
 			Namval_t* np;
-			if(!lp->lex.incase && !assignment && fcpeek(0)!=LPAREN &&
+			if((!lp->lex.incase || lp->lex.incase==2) && !assignment && fcpeek(0)!=LPAREN &&
 				(np=nv_search(state,shp->alias_tree,HASH_SCOPE))
 				&& !nv_isattr(np,NV_NOEXPAND)
 #if KSHELL
```
However, the W alias is still not substituted:
```
$ arch/*/bin/ksh -c "alias C='case ' W='x ' I='in '; eval 'C W I x) echo ok;; W) echo wrong;; *) echo bad;; esac'"        
wrong
```
And when we apply the patch from the previous comment instead (removing the check altogether), the behaviour changes to:
```
$ arch/*/bin/ksh -c "alias C='case ' W='x' I='in '; eval 'C W I x) echo ok;; W) echo wrong;; *) echo bad;; esac'"
bad
```
All this confirms for me I should not be touching this. I can't imagine a convincing use case and the risk of side effects is too great.

**Comment by oguz-ismail** [comment]
> I see your point about the aliases ending in whitespace. But I think the standard is very unclear. I'll note that it doesn't work on zsh, either.

I agree that the standard is unclear, but zsh shouldn't be a yardstick when standard conformance is concerned.

> Note that in the next version of the standard, any alias whose value is not a simple command (or contains an assignment or redirection) will produce unspecified behaviour. See: https://www.austingroupbugs.net/view.php?id=953#c4214 (scroll up for preceding discussion).

That *If the value of the alias cannot be tokenized as a simple command* part is not included in 202x draft.

> So, with the current standard being unclear and the next version of the standard very probably making this explicitly unspecified, I don't think standards compliance is relevant.
> 
> That is no reason not to fix this in and of itself, but I'd like to see an actual use case that breaks because of this. If no use case can be demonstrated, I'm reluctant to touch this.

This, I understand. Thanks for looking into it anyway
