### ISSUE TITLE
Re-allow building dynamic libraries

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#302]
The build system needs to be adapted to re-allow building libast, libcmd, libdll and libsum as dynamic libraries, without requiring nmake to do so. Some systems (at least some illumos distrubutions) skip ksh93 that way.

It is also necessary for dynamically loadable custom builtins to work properly; with static linking they are statically linked to their own copies of libshell/libast, and multiple copies of those do not play well together.

A quick look in the [ast-open-history repo](https://github.com/ksh93/ast-open-history) makes it seem that it used to be possible to build dynamic libraries without nmake, but that functionality was removed. Perhaps we can re-implement it based on that old code.

**Comment by lkujaw** [comment]
Hi Martijn,

Sorry I haven't been active with the ksh93 project recently, but I thought I should chime in since I recently started working to restore nmake support for newer platforms. The dynamic linking code within the nmake base rules is heavily dependent upon nmake conditional statements, and thus .SHARED.ON. is hardwired to report false when  `$(-mam:N=static*,port*)` is true. There is code within Makerules.mk to emit hand-written Mam-compatible shell conditionals to cover the needs of AST, but it seems clear to me that Mamfiles were only intended to serve as a bootstrapping mechanism and thus support only the most rudimentary functionality for that end.

Kind regards, Lev
