### ISSUE TITLE
ksh93 misbehaves when stdout is closed

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#314]
As noted in this [austin-group-l discussion](https://www.mail-archive.com/austin-group-l@opengroup.org/msg08056.html) (relevant to this issue):

```
$ ksh93u+m -c 'pwd; echo "$?" >&2; echo test; echo "$?" >&2' >&-
0
1
/home/chazelas
```

when stdout is closed, pwd does claim it succeeds (by returning a 0 exit status), while echo doesn't (not really relevant to the problem here, only to show it doesn't affect all builtins), and the output that pwd failed to write earlier ends up being written on stderr here instead of stdout upon exit (presumably) because of that >&2 redirection.

`strace` shows ksh93 attempting `write(1, "/home/chazelas\n", 15)` 6 times (1, the last one, successful).

It gets even weirder when redirecting to a file:

```
$ ksh93u+m -c 'pwd; echo "$?" >&2; echo test; echo "$?" > file' >&-
0
$ cat file
1
1
ome/chazelas
```

**Comment by McDutchie** [comment]
In my testing, the problem does not occur when closing stdout at the start of the `-c` script itself (using `redirect >&-` or `exec >&-`); it only occurs if stdout was closed before initialising the shell.

That made me suspect that the problem had to do with an inconsistent file descriptor state in the shell. ksh uses internal [`sh_open()`](https://github.com/ksh93/ksh/blob/77827c53e2dc675020e27fd6e9c857f692ee6704/src/cmd/ksh93/sh/io.c#L753-L886) and [`sh_close()`](https://github.com/ksh93/ksh/blob/77827c53e2dc675020e27fd6e9c857f692ee6704/src/cmd/ksh93/sh/io.c#L702-L731) functions, among others, to maintain that state.

I understand very little about all that, but maybe that's enough. The following patch appears to fix the output corruption bug:

```diff
diff --git a/src/cmd/ksh93/sh/main.c b/src/cmd/ksh93/sh/main.c
index dfa5fc25..b2ad4c14 100644
--- a/src/cmd/ksh93/sh/main.c
+++ b/src/cmd/ksh93/sh/main.c
@@ -344,6 +344,10 @@ int sh_main(int ac, char *av[], Shinit_f userinit)
 				sh_accbegin(error_info.id);
 #endif	/* SHOPT_ACCT */
 		}
+		/* If the shell is init'ed with std{in,out,err} closed, make the shell's FD state reflect that. */
+		for(i=0; i<=2; i++)
+			if(fcntl(i,F_GETFD,NiL)==-1 && errno==EBADF)	/* closed at OS level? */
+				sh_close(i); 				/* update shell FD state */
 	}
 	else
 	{
```

Another part of this issue is that a few built-ins that write output (at least `pwd`, `whence`, `trap`) still need to be fixed to exit with a non-zero status (and maybe an error message) upon I/O error.
