### ISSUE TITLE
[question, documentation, bug] unusual/non-standard error message

### ISSUE THREAD

**Issue by XSven** [ksh93/ksh#315]
```
ksh93 --version
  version         sh (AT&T Research) 93t+ 2009-05-01

uname -s
AIX
```
In the vim Syntastic plugin the `ksh93 -n` syntax checker is based on the errorformat variable. Recently I was involved in the modification of this variable to improve parsing ksh93 warning and error messages. The checker is now able to detect warnings (exit status 0)

`todo.sh: warning: line 3: -eq within [[...]] obsolete, use ((...))`

errors (exit status 3)

``broken.sh: syntax error at line 8: `{' unmatched``

Now by accident I was able to provoke another kind of error (exit status 1)

`broken.sh:  0 = 0 : assignment requires lvalue`

I know what I have done wrong syntactically. I do not understand the exit status. Why is it 1 instead of 3? Why is the line number information missing in the message and why does the message not state that it is a **syntax error**?

**Comment by hyenias** [comment]
Can you please provide some example script code to us that reproduces those particular situations you have referenced? This will provide a better understanding of what is going on. Otherwise, please install and use our version of ksh93 which is ksh93+um as it might have already remedied some or all of your troubles as your ksh93t version is very old.

**Comment by XSven** [comment]
```
# warning (exit status 1)
/usr/bin/ksh93 -n -c '[[ 0 -eq 0 ]]  && true'
/usr/bin/ksh93: warning: line 1: -eq within [[...]] obsolete, use ((...))

# syntax error  (exit status 3)
/usr/bin/ksh93 -n -c 'say() {'
/usr/bin/ksh93: syntax error at line 1: `{' unmatched

# unusual syntax error (exit status 1)
/usr/bin/ksh93 -n -c '(( 0 = 0 )) && true'
/usr/bin/ksh93:  0 = 0 : assignment requires lvalue

```

We are using the vendor (IBM) supplied ksh93 that we cannot replace. First of all I want to understand the situation that means I am not yet saying that I have detected a bug!

**Comment by hyenias** [comment]
For me, your 1st reproducer appears to be fixed in the current ksh93u+m version. Note: the `-n` option indicates, "The shell reads commands and checks for syntax errors, but does not execute the command. Usually specified on command invocation." This test does not have a syntax error and can be run as-is returning the correct exit status.
```ksh
$ ksh -nc '[[ 0 -eq 0 ]]'; echo $?
ksh: warning: line 1: -eq within [[ ... ]] obsolete, use ((...))
0
$ ksh -nc '[[ 0 -eq 1 ]]'; echo $?
ksh: warning: line 1: -eq within [[ ... ]] obsolete, use ((...))
0
$ ksh -c '[[ 0 -eq 0 ]]'; echo $?
0
$ ksh -c '[[ 0 -eq 1 ]]'; echo $?
1
$
```
For your 2nd reproducer, I have the following results as well. I do not possess the knowledge of why 3 is assigned as the exit status instead of another 1-255 integer.
```ksh
$ ksh -n -c 'say() {'; echo $?
ksh: syntax error at line 1: `{' unmatched
3
$
```
For your 3rd one, it seems that the `-n` syntax check is not finding the arithmetic assignment error having an invalid variable name. And as you noted, the return status is 1 when perhaps you are expecting a greater exit status code which would seem to be more meaningful.
```ksh
$ ksh -nc '(( 0 == 0 ))'; echo $?
0
$ ksh -nc '(( 0 = 0 ))'; echo $?
0
$ ksh -c '(( 0 == 0 ))'; echo $?
0
$ ksh -c '(( 0 = 0 ))'; echo $?
ksh:  0 = 0 : assignment requires lvalue
1
$
```

**Comment by XSven** [comment]
Excerpt of section 6.2.2. Arithmetic Conditionals of the O'REILLY Korn Shell book

`((...)) is almost identical to $((...)). However, it was designed for use in if and while constructs. Instead of producing a textual result, it just sets its exit status according to the truth of the expression: 0 if true, 1 otherwise. 
`

Now we know what the exits status 1 means.  My ksh93t has a bug

```
$ ksh93 -nc '(( 0 = 0 ))'; echo $?
ksh93:  0 = 0 : assignment requires lvalue
1
```
because although it should check the syntax (`-n`) only it seems to evalutate the arithmetic condition and although the condition is invalid it is interpreted as false (`1`).

Syntax checking of the ksh93u+m does not consider arithmetic conditions.

```
$ ksh -nc '(( 0 = 0 ))'; echo $?
0
```

Is this a bug or a feature?

ksh93u+m executes an invalid arithmetic condition and considers this as a false (`1`) although the condition is invalid.

```
$ ksh -c '(( 0 = 0 ))'; echo $?
ksh:  0 = 0 : assignment requires lvalue
1
```

As long as this behaviour is not explicitly described and documented, I think this is a bug.

**Comment by McDutchie** [comment]
Top comment:
> I know what I have done wrong syntactically. I do not understand the exit status. Why is it 1 instead of 3? Why is the line number information missing in the message and why does the message not state that it is a **syntax error**?

Since arithmetic expressions are not part of the shell language itself, they don't throw a regular syntax error. The arithmetic subsystem is its own little subset of C within the shell language.

Previous comment:
> ksh93u+m executes an invalid arithmetic condition and considers this as a false (`1`) although the condition is invalid.
> 
> ```
> $ ksh -c '(( 0 = 0 ))'; echo $?
> ksh:  0 = 0 : assignment requires lvalue
> 1
> ```
> 
> As long as this behaviour is not explicitly described and documented, I think this is a bug.

Actually, it exits the shell after issuing that error message. You didn't notice this because the `echo $?` was outside of the `-c` script executed by the child shell. Try something like:

```
$ ksh -c '(( 0 = 0 )); echo end'
ksh:  0 = 0 : assignment requires lvalue
```

The `end` is not printed because the error causes the script to abort.

So in 93u+ (and thus also in 93u+m) the error in the arithmetic subsystem is detected at run time instead of parse time. This is not really worse, it's just different. In fact it makes more sense to me this way precisely because the arithmetic sub-language is not part of the shell language itself. Anything in an arithmetic expression can be expanded from a variable (for example, `(($foo = 0))` is perfectly valid if the value of `$foo` is a variable name), so we can't reliably detect these errors at parse time.

As for the remainder of your 93t+ questions, I don't know the answer. That ksh version is ancient, very buggy, and not supported here. If IBM still ships it, it's up to them to support it, so hopefully you can get an answer from them. Since there's nothing for 93u+m development to do with this issue, I'll close it now.
