### ISSUE TITLE
 Use real pipes instead of sockets

### ISSUE THREAD

**Issue by casantos** [ksh93/ksh#327]
This is a duplication of [issue #462](https://github.com/att/ast/issues/462) in the old AST project.

Ksh uses sockets instead of real pipes to implement pipes in shell. This has caused issues on multiple occasions. For e.g.

> `$ cat /etc/passwd | head -1 /dev/stdin`
> `head: cannot open '/dev/stdin' for reading: No such device or address`

I understand that switching to real pipes may cause regressions, so I don't expect to see a fix anytime soon.

**Comment by hyenias** [comment]
Just tested out this above reproducer and it works on  my macOS and FreeBSD systems but fails as mentioned on my Debian Linux based systems. I created a foo.txt file containing: _foo_, _bar_, and _you_ lines of text instead of playing around with my password file.

macOS/FreeBSD: work
```
$ cat foo.txt
foo
bar
you
$ cat foo.txt | head -1 /dev/stdin
foo
```
Debian Linux based systems: fail using /dev/stdin
```
$ cat foo.txt | head -1 /dev/stdin
head: cannot open '/dev/stdin' for reading: No such device or address
$ cat foo.txt | head -1
foo
$ cat foo.txt | head -1 -
foo
```
Is there a particular need to pass **/dev/stdin** as a file with head?

**Comment by casantos** [comment]
> Just tested out this above reproducer and it works on my macOS and FreeBSD systems but fails as mentioned on my Debian Linux based systems. I created a foo.txt file containing: _foo_, _bar_, and _you_ lines of text instead of playing around with my password file.
> 
> macOS/FreeBSD: work
> 
> ```
> $ cat foo.txt
> foo
> bar
> you
> $ cat foo.txt | head -1 /dev/stdin
> foo
> ```

That's because on macOS `/dev/stdin` is a named pipe, as shown by
```
$ ksh -c ' echo OK | file /dev/fd/0'
/dev/fd/0: fifo (named pipe)
```
> Debian Linux based systems: fail using /dev/stdin
> 
> ```
> $ cat foo.txt | head -1 /dev/stdin
> head: cannot open '/dev/stdin' for reading: No such device or address
> $ cat foo.txt | head -1
> foo
> $ cat foo.txt | head -1 -
> foo
> ```

On Linux ksh uses a socket, e.g.

```
$ ksh -c 'echo OK | ls -l /dev/fd/0'
lrwx------. 1 testuser testuser 64 Oct 19 21:04 /dev/fd/0 -> 'socket:[2621789]'
```
> Is there a particular need to pass **/dev/stdin** as a file with head?

I'm a software maintenance engineer at Red Hat and some of our customers have this construction in their custom scripts. This is mostly legacy software ported from other Unix versions that system administrators understandably feel afraid to change.

**Comment by hyenias** [comment]
Here are my results on my machines:
```
# Debian Linux
$ echo OK | file /dev/fd/0
/dev/fd/0: symbolic link to socket:[67886]
$
# macOS
echo OK | file /dev/fd/0
/dev/fd/0: socket
echo OK | file /dev/stdin
/dev/stdin: socket
$
# FreeBSD
$ echo OK | file /dev/fd/0
/dev/fd/0: character special (0/15)
$ echo OK | file /dev/stdin
/dev/stdin: symbolic link to fd/0
$
```
Also, head's syntax differs a tad on FreeBSD. So, the following works correctly across all of my systems. The `-1` option is legacy and should be rewritten as `-n 1` and the `-` was not available on FreeBSD's head version.
```
$ cat foo.txt | head -n 1
foo
```

**Comment by casantos** [comment]
The problem on Linux is that you can't open()/openat() a socket.

In kernel 2.6.32 it's in net/socket.c:

```
static int sock_no_open(struct inode *irrelevant, struct file *dontcare);
[...]
static const struct file_operations socket_file_ops = {
        .owner =        THIS_MODULE,
        .llseek =       no_llseek,
        .aio_read =     sock_aio_read,
        .aio_write =    sock_aio_write,
        .poll =         sock_poll,
        .unlocked_ioctl = sock_ioctl,
#ifdef CONFIG_COMPAT
        .compat_ioctl = compat_sock_ioctl,
#endif
        .mmap =         sock_mmap,
        .open =         sock_no_open,   /* special open code to disallow open via /proc */
        .release =      sock_close, 
        .fasync =       sock_fasync,
        .sendpage =     sock_sendpage,
        .splice_write = generic_splice_sendpage, 
        .splice_read =  sock_splice_read,
};
[...]
/*
 *      In theory you can't get an open on this inode, but /proc provides
 *      a back door. Remember to keep it shut otherwise you'll let the
 *      creepy crawlies in.
 */

static int sock_no_open(struct inode *irrelevant, struct file *dontcare)
{       
        return -ENXIO;  
}       
```

In kernel 3.10.0 and 4.18.0, it's in fs/inode.c, if I understood it correctly:

```
static int no_open(struct inode *inode, struct file *file)
{
        return -ENXIO;
}

/**
 * inode_init_always - perform inode structure initialisation
 * @sb: superblock inode belongs to
 * @inode: inode to initialise
 *
 * These are initializations that need to be done on every inode
 * allocation as the fields are not initialised by slab allocation.
 */
int inode_init_always(struct super_block *sb, struct inode *inode)
{
        static const struct inode_operations empty_iops;
        static const struct file_operations no_open_fops = {.open = no_open};
        struct address_space *const mapping = &inode->i_data;

        inode->i_sb = sb;
        inode->i_blkbits = sb->s_blocksize_bits;
        inode->i_flags = 0;
        atomic64_set(&inode->i_sequence, 0);
        atomic_set(&inode->i_count, 1);
        inode->i_op = &empty_iops;
        inode->i_fop = &no_open_fops;
[...]
void init_special_inode(struct inode *inode, umode_t mode, dev_t rdev)
{
        inode->i_mode = mode;
        if (S_ISCHR(mode)) {
                inode->i_fop = &def_chr_fops; 
                inode->i_rdev = rdev;
        } else if (S_ISBLK(mode)) {
                inode->i_fop = &def_blk_fops;
                inode->i_rdev = rdev;
        } else if (S_ISFIFO(mode))
                inode->i_fop = &pipefifo_fops;
        else if (S_ISSOCK(mode))
                ;       /* leave it no_open_fops */
        else
                printk(KERN_DEBUG "init_special_inode: bogus i_mode (%o) for"
                                  " inode %s:%lu\n", mode, inode->i_sb->s_id,
                                  inode->i_ino);
```

**Comment by McDutchie** [comment]
I was tempted to say this is a Linux problem, not a ksh problem. But, unfortunately, Linux's refusal to `open`(2)/`openat`(2) a socket is [allowed by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html#tag_16_357_05). So we have to deal with it somehow.

To make ksh use real pipes, all you have to do is make the `pipe_socketpair` feature test return unsuccessfully:
```diff
diff --git a/src/cmd/ksh93/features/poll b/src/cmd/ksh93/features/poll
index e14920ba..c3c7a100 100644
--- a/src/cmd/ksh93/features/poll
+++ b/src/cmd/ksh93/features/poll
@@ -23,6 +23,7 @@ tst	pipe_socketpair note{ use socketpair() for peekable pipe() }end execute{
 	}
 	int main()
 	{
+		return 1;
 		int		n;
 		int		pfd[2];
 		int		sfd[2];
```

(Search the code for `#if _pipe_socketpair` to find the relevant code.)

The problem is that using a real pipe kills `read -n` (read a number of bytes) because (as far as I understand it) it is not possible to peek ahead on a pipe. For the same reason it also kills `<#`*pattern* redirections for pipes. And surely there are scripts that rely on one of these as well. This is reflected in the following regression test failures:
```
	io.sh[243]: <# not working for pipes
	io.sh[338]: read -n3 from pipe not working
	io.sh[347]: read -n3 from fifo failed -- expected 'a', got 'abc'
	io.sh[350]: read -n1 from fifo failed -- expected 'b', got 'd'
	io.sh[380]: should have timed out
	io.sh[381]: line1 should be 'prompt1: '
	io.sh[382]: line2 should be line2
	io.sh[383]: line3 should be 'prompt2: '
	io.sh[407]: LC_ALL=C read -n2 from pipe 'a bcd' failed -- expected 'a bcd', got 'ab cd'
	io.sh[407]: LC_ALL=C.UTF-8 read -n2 from pipe 'a bcd' failed -- expected 'a bcd', got 'ab cd'
```

**Comment by McDutchie** [comment]
It may or may not be possible to fix the above regressions using real pipes, but in any case I don't know how.

So for now the only thing to do is to fix it in POSIX mode only, and document the resulting breakage.

How to do that?

In io.c, `pipe()` is redefined with a macro to use a socket pair if available (and if the system's native pipes don't support peeking like they do on Solaris): https://github.com/ksh93/ksh/blob/9b259c944e2b4ffb2db7cdbfb84d0fb0645949db/src/cmd/ksh93/sh/io.c#L89-L101

The original `pipe()` function that creates a real pipe is made available via `sh_rpipe()`: https://github.com/ksh93/ksh/blob/9b259c944e2b4ffb2db7cdbfb84d0fb0645949db/src/cmd/ksh93/sh/io.c#L942-L967

So, the following simple patch should make ksh use real pipes in POSIX mode:

```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1985,7 +1985,10 @@ int sh_exec(register const Shnode_t *t, int flags)
 			do
 			{
 				/* create the pipe */
-				sh_pipe(pvn);
+				if(sh_isoption(SH_POSIX))
+					sh_rpipe(pvn);
+				else
+					sh_pipe(pvn);
 				/* execute out part of pipe no wait */
 				(t->lst.lstlef)->tre.tretyp |= showme;
 				type = sh_exec(t->lst.lstlef, errorflg);
```

**Comment by hyenias** [comment]
Shouldn't this change be limited to Linux as it seems to me that FreeBSD and macOS work correctly with sockets? Just checking to see the resulting impact of the patch. Will ksh now use named pipes in POSIX mode across-the-board for everything?

**Comment by McDutchie** [comment]
No, not named pipes, just pipes. Named pipes have an entry in the file system, normal pipes don't.

POSIX requires pipes, apparently, so it should be done on all systems. Linux might be the only system that we currently know of where you can't `open`(2) a socket, but that doesn't mean there aren't or won't be others. Plus, other programs might check for a pipe using `fstat`(2) and `S_ISFIFO`, which will not check out for a socket on any system.

**Comment by hyenias** [comment]
Good to know. Thank you for the clarification.

**Comment by leahneukirchen** [comment]
FWIW, other shells implement `read -n` by reading single bytes in a loop. This seems to be the only portable way; actually ksh will fall back to this when stdin is a pipe.

**Comment by casantos** [comment]
> FWIW, other shells implement `read -n` by reading single bytes in a loop. This seems to be the only portable way; actually ksh will fall back to this when stdin is a pipe.

That's interesting. I confirmed it on RHEL-8 with
```
$ strace -ftttTvyyo /tmp/bash-ksh-pipe.strace bash -c "echo 1234567890 | ksh -c 'read -n 8 x; echo \$x;'"
$ cat /tmp/bash-ksh-pipe.strace
...
178605 1637763489.732498 write(1<pipe:[4227890]>, "1234567890\n", 11 <unfinished ...>
[...]
178605 1637763489.732644 <... write resumed>) = 11 <0.000084>
[...]
178606 1637763489.748949 recvfrom(0<pipe:[4227890]>, 0x7f461319b9b0, 8, MSG_PEEK, NULL, NULL) = -1 ENOTSOCK (Socket operation on non-socket) <0.000022>
178606 1637763489.749056 read(0<pipe:[4227890]>, "1", 1) = 1 <0.000034>
178606 1637763489.749166 read(0<pipe:[4227890]>, "2", 1) = 1 <0.000016>
178606 1637763489.749253 read(0<pipe:[4227890]>, "3", 1) = 1 <0.000016>
178606 1637763489.749332 read(0<pipe:[4227890]>, "4", 1) = 1 <0.000016>
178606 1637763489.749409 read(0<pipe:[4227890]>, "5", 1) = 1 <0.000016>
178606 1637763489.749486 read(0<pipe:[4227890]>, "6", 1) = 1 <0.000034>
178606 1637763489.749588 read(0<pipe:[4227890]>, "7", 1) = 1 <0.000016>
178606 1637763489.749672 read(0<pipe:[4227890]>, "8", 1) = 1 <0.000016>
178606 1637763489.749814 write(1</dev/pts/0<char 136:0>>, "12345678\n", 9) = 9 <0.000031>
```

**Comment by ormaaj** [comment]
There's `ungetc()` for pipes but as I recall it has a lot of not so nice quirks as well. I thought the `AF_UNIX` sockets came into play in order to implement things like `${ ;}` and that's a pretty essential feature.

Other options to look at might be `mmap` and posix message queues. No clue what the considerations are for these but I'm guessing there's a reason they aren't already being utilized.

As a side-note, a (likely linux specific) feature I learned about recently is the `lseek(2)` `whence` parameter's `SEEK_DATA` . That apparently allows you to supply an arbitrary terminator character and with a single syscall the kernel hunts for the end offset for you.

The intended purpose was apparently for handling sparse files but in theory you could then rewind the file to the initial offset and use the known seek distance for a huge speedup to `read` including any `read -d 'x'`, possibly `IFS=x read -[nN]` for the special case of a single byte `IFS`, special cases of `<#` redirects, and probably other things.

If that feature were exposed by system libc's it would probably be possible to expand platform support and eventually use it. Right now it sounds like not even all linux filesystems are supported. (Yuck, per-filesystem implementation??? You'd think this would be higher up in the VFS layer.)

**Comment by McDutchie** [comment]
A better patch for real pipes in POSIX mode, which handles all cases:
```diff
diff --git a/src/cmd/ksh93/sh/io.c b/src/cmd/ksh93/sh/io.c
index 4d26420b5..05ea03635 100644
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -913,6 +913,10 @@ int sh_iomovefd(register int fdold)
 int	sh_pipe(register int pv[])
 {
 	int fd[2];
+#ifdef pipe
+	if(sh_isoption(SH_POSIX))
+		return(sh_rpipe(pv));
+#endif
 	if(pipe(fd)<0 || (pv[0]=fd[0])<0 || (pv[1]=fd[1])<0)
 	{
 		errormsg(SH_DICT,ERROR_system(1),e_pipe);
```

**Comment by McDutchie** [comment]
leahneukirchen wrote:
> FWIW, other shells implement `read -n` by reading single bytes in a loop. This seems to be the only portable way; actually ksh will fall back to this when stdin is a pipe.

But there is still something that breaks when using real pipes. Reproducer:
```
(print -n a; sleep .1; print -n bcde) 2>/dev/null | read -n3 var
print "$var"
```
The expected output is `a`. When using real pipes, the output is `abc`.

That's because the `sleep .1` is supposed to cause `read -n` to time out. According to the manual page: 
```
              -n      Causes at most n bytes to be  read  instead  of  a  full
                      line, but will return when reading from a slow device as
                      soon as any characters have been read.
```
So with a real pipe, it fails to detect a "slow device".

**Comment by McDutchie** [comment]
I've now fixed it for the POSIX mode which will close this issue.

Perhaps in the future I'll find a way for sh_exec() to analyse the parse tree so that ksh can decide on a case-by-case basis whether to use socketpair(2) instead of pipe(2) based on which commands or redirections are used. Since those features are all built-in and non-POSIX, that should be good enough. But for now, that is beyond me.
