### ISSUE TITLE
[doc] document %#P or fix documention of %(pattern)q in printf

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#338]
`printf --man` describes `%(pattern)q` as

>         %(pattern)q
>               Equivalent to %#P.

But doesn't say what `%#P` does. 

From looking at the code, it seems to me `%#P` is no different from `%P`.

If that's indeed the case, the documentation above should be:

>         %(pattern)q
>               Equivalent to %P.

To avoid confusion.

**Comment by McDutchie** [comment]
I can't find any difference either. `#` is an "alternative format specifier" and no alternative format is documented for `%P`, so it seems like it's ignored.

**Comment by McDutchie** [comment]
Also, look at where that documentation comes from: it's dynamically generated from this struct via the `infof` discipline function! Interesting. https://github.com/ksh93/ksh/blob/0f06a2e91b9918d3347a5bed1d8541bfda84d020/src/cmd/ksh93/bltins/print.c#L77-L85

In the two other entries with a `#`, that's mapped to an additional `+`, but not in the `%#P` one. So that's another indication it should probably be `#P`. (I can't easily find where that `+` is parsed. Possibly somewhere in libast.)

Plus, it looks like they already changed it to `#P` in ksh 93v-.
