### ISSUE TITLE
Signal incorrectly issued when function returns with status > 256 and EXIT trap is active

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#364]
This bug is a regression introduced in commit 30aee651. The following script will cause ksh93u+m to segfault rather than print 'OK': 
```sh
$ cat /tmp/exit267
trap 'echo OK' EXIT  # This trap triggers the crash
function foo { return 267; }
foo
$ bash /tmp/exit267
OK
$ ksh-3aee10d7 /tmp/exit267
OK
$ ksh /tmp/exit267
Memory fault(coredump)
```

I used `gdb` and the backtrace pointed to this section of code as being at fault:
https://github.com/ksh93/ksh/blob/f22f623a0f0f56749d4ea40b80ad5e74f163a920/src/cmd/ksh93/sh/xec.c#L3257-L3258

**Comment by JohnoKing** [comment]
I've found a related problem that occurs because of this bug. If an `EXIT` trap is active and a program exits with a segmentation fault then ksh will exit by killing itself with SIGSEGV as well:
```sh
$ cat /tmp/bar
trap : EXIT
function foo {
	sh -c 'kill -SEGV $$'
}
foo 2> /dev/null
echo OK

$ ksh /tmp/bar
Memory fault(coredump)
$ bash /tmp/bar
OK
```

**Comment by McDutchie** [comment]
I would say this bug (or purposeful behaviour) was not so much introduced, but exposed by that commit. On 93u+ 2012-08-01, the same behaviour occurs if you issue SIGINT or SIGQUIT:
```
$ cat /tmp/exitsig         
echo $KSH_VERSION$BASH_VERSION$ZSH_VERSION$YASH_VERSION
trap 'echo OK' EXIT  # This trap triggers the signal
function foo { return $((256 + $1)); }
case $1 in
*[!0-9]*)  foo $(kill -l $1) ;;
*)         foo $1 ;;
esac
$ /bin/ksh /tmp/exitsig QUIT
Version AJM 93u+ 2012-08-01
OK
Quit
```
(note the `Quit` is macOS reporting that the process was terminated by SIGQUIT).

As noted in the 30aee65113e47832060ac1ea6ee72fd47ef4897a commit message, the manual says that "A trap condition that is not caught or ignored by the function causes the function to terminate and the condition to be passed on to the caller". Reissuing the signal is ksh's current way of doing this. 

Perhaps the behaviour you're reporting is what they meant to fix or mitigate by limiting the propagation of signals from functions to `SIGINT` or `SIGQUIT`. But if so, their fix was wrong as it broke traps instead. 

ksh detects whether a signal was sent by checking if the function's exit status is > 256 (i.e.: does not fit in `SH_EXITMASK`). That check is what's actually broken, as such an exit status may occur without a signal being sent.

So I stand behind commit 30aee65113e47832060ac1ea6ee72fd47ef4897a. But we may need to fix how ksh detects if a signal was sent, or how the trap condition is passed down to the caller.

Either that, or we simply disallow `return` ~~and `exit`~~ from issuing an exit status > 256 by bitmasking their arguments to 255 (`SH_EXITMASK`) (*edit:* this was already fixed for `exit` in d024d4c895ca78df173d0ee71fa95fbe8089944d). I think there is a good argument to be made that they shouldn't be allowed to set the `SH_EXITSIG` bit. But could that cause significant backwards compatibility problems?

**Comment by McDutchie** [comment]
It's worth seeing how the offending lines of code changed throughout the ast-open-history repo.

Prior to 2010-10-10: https://github.com/ksh93/ast-open-history/blob/0722f269f72fe174e2eeedf5f26e0aea2e45e0cb/src/cmd/ksh93/sh/xec.c#L3225-L3226 - there is no broken check for SIGINT/SIGQUIT and the condition is propagated using sh_fault(), not by actually reissuing the signal.

2010-10-10: https://github.com/ksh93/ast-open-history/blob/37b788b620fce0a1c473332e8c1e4163487cf005/src/cmd/ksh93/sh/xec.c#L3225-L3228 - adds check for jmpval as well as that broken SIGINT/SIGQUIT check.

2012-06-28: https://github.com/ksh93/ast-open-history/blob/aefddbd4179836641d65790c42db3545fb4dabbb/src/cmd/ksh93/sh/xec.c#L3457-L3460 - changes from using sh_fault() to reissuing signal to self. I wonder what the problem was with using sh_fault().

**Comment by McDutchie** [comment]
>  I think there is a good argument to be made that [`return`] shouldn't be allowed to set the SH_EXITSIG bit. But could that cause significant backwards compatibility problems?

Right, I think we're allowed to solve this the simple way and disallow exit statuses greater than fit into 8 bits (0-255) for `return`. Because, `return --man` already documents under `EXIT STATUS`, as it also did in 93u+:

> If *n* is specified, the exit status is the least significant eight bits of the value of *n*.

And sh.1 says, under `return`:

> The value will be the least significant 8 bits of the specified status.

That's unambiguous. `return` is not behaving as documented, hence this bug.

**Comment by McDutchie** [comment]
The bug is caused by this code in b_return(): https://github.com/ksh93/ksh/blob/a874f8c16989079143ceeae52c2ba6ffde1ce3f8/src/cmd/ksh93/bltins/cflow.c#L71-L73 …which (going by the [multishell repo](https://github.com/multishell/ksh93)) was added in version 2012-07-27: https://github.com/multishell/ksh93/commit/410f8e220f6410b835e840b751340abb89274e35

The only related changelog entry is:
```
12-07-02  A bug in which an exit status > 256 corresponding to a signal was
          not returned by a function to indicate a signal exit has been fixed.
```

But that looks like nonsense to me. This change was made in the `return` builtin, and `return` should not be able to cause any signals to be emitted.

At the same time, there are [two regression tests in functions.sh](https://github.com/ksh93/ksh/blob/a874f8c16989079143ceeae52c2ba6ffde1ce3f8/src/cmd/ksh93/tests/functions.sh#L1213-L1233) that claim that `return 267` and `return 271` should work. Note that `return 256` explicitly does not work, though, and neither does any value past the signal range. How inconsistent.

Either we reinstate the 8-bit limitation, though the regression tests suggest that might cause backwards compatibility problems by now -- or we find another solution.

I think I found another solution. In the offending xec.c lines, I believe we can simply use the `sh.lastsig` (a.k.a. `shp->lastsig`) variable instead; it contains the last signal that was actually sent since the execution of the last command. This variable gets reset at every sh_exec() invocation, i.e., before any command is executed.

Then in the `return` command we can simply not limit the value, and it should never cause any signal to be emitted. So you can now use any return value that fits in your system's int.

Please test (I'm aware the documentation updates are still missing):

(*edit:* patch updated to correct silly mistake causing a segfault)

```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -3254,8 +3254,8 @@ int sh_funscope(int argn, char *argv[],int(*fun)(void*),void *arg,int execflg)
 	}
 	if(jmpval)
 		r=shp->exitval;
-	if(nsig && r>SH_EXITSIG)
-		kill(shgd->current_pid,r&SH_EXITMASK);
+	if(sh.lastsig)
+		kill(shgd->current_pid, sh.lastsig);
 	if(jmpval > SH_JMPFUN)
 	{
 		sh_chktrap(shp);
--- a/src/cmd/ksh93/bltins/cflow.c
+++ b/src/cmd/ksh93/bltins/cflow.c
@@ -44,12 +44,11 @@
     /* for the dictionary generator */
     int	b_exit(int n, register char *argv[],Shbltin_t *context){}
 #endif
-int	b_return(register int n, register char *argv[],Shbltin_t *context)
+noreturn int	b_return(int n, char *argv[], Shbltin_t *context)
 {
-	register char *arg;
-	register Shell_t *shp = context->shp;
-	struct checkpt *pp = (struct checkpt*)shp->jmplist;
+	struct checkpt *pp = (struct checkpt*)sh.jmplist;
 	const char *options = (**argv=='r'?sh_optreturn:sh_optexit);
+	NOT_USED(context);
 	while((n = optget(argv,options))) switch(n)
 	{
 	    case ':':
@@ -66,17 +65,21 @@ done:
 		errormsg(SH_DICT,ERROR_usage(2),"%s",optusage((char*)0));
 		UNREACHABLE();
 	}
-	pp->mode = (**argv=='e'?SH_JMPEXIT:SH_JMPFUN);
-	argv += opt_info.index;
-	n = (arg = *argv) ? (int)strtol(arg, (char**)0, 10) : shp->savexit;
-	if(n<0 || n==256 || n > SH_EXITMASK+shp->gd->sigmax+1)
-			n &= ((unsigned int)n)&SH_EXITMASK;
+	if(argv[opt_info.index] && *argv[opt_info.index])
+		n = (int)strtol(argv[opt_info.index], NIL(char**), 10);
+	else
+		n = sh.savexit;	/* pass down $? */
 	/* return outside of function, dotscript and profile is exit */
-	if(shp->fn_depth==0 && shp->dot_depth==0 && !sh_isstate(SH_PROFILE))
+	if(**argv=='e' || (sh.fn_depth==0 && sh.dot_depth==0 && !sh_isstate(SH_PROFILE)))
+	{
 		pp->mode = SH_JMPEXIT;
-	shp->savexit = n;
-	sh_exit((pp->mode == SH_JMPEXIT) ? (n & SH_EXITMASK) : n);
-	return(1);
+		n &= SH_EXITMASK;
+	}
+	else
+		pp->mode = SH_JMPFUN;
+	sh.savexit = n;
+	sh_exit(n);
+	UNREACHABLE();
 }
 
 
--- a/src/cmd/ksh93/tests/functions.sh
+++ b/src/cmd/ksh93/tests/functions.sh
@@ -1210,11 +1210,10 @@ function foo
 	let 1
 	return $1
 }
-invals=(135 255 256 267 -1)
-outvals=(135 255 0 267 255)
-for ((i=0; i < ${#invals[@]}; i++))
-do	foo ${invals[i]}
-	[[ $? == "${outvals[i]}" ]] || err_exit "function exit ${invals[i]} should set \$? to ${outvals[i]}"
+vals=(135 255 256 267 -1)
+for ((i=0; i < ${#vals[@]}; i++))
+do	foo ${vals[i]}
+	[[ $? == "${vals[i]}" ]] || err_exit "function exit ${vals[i]} should set \$? to ${vals[i]}"
 done
 
 function foo
--- a/src/cmd/ksh93/include/builtins.h
+++ b/src/cmd/ksh93/include/builtins.h
@@ -74,7 +74,7 @@ extern int b_dot_cmd(int, char*[],Shbltin_t*);
 extern int b_enum(int, char*[],Shbltin_t*);
 extern int b_exec(int, char*[],Shbltin_t*);
 extern int b_eval(int, char*[],Shbltin_t*);
-extern int b_return(int, char*[],Shbltin_t*);
+extern noreturn int b_return(int, char*[],Shbltin_t*);
 extern int B_login(int, char*[],Shbltin_t*);
 extern int b_true(int, char*[],Shbltin_t*);
 extern int b_false(int, char*[],Shbltin_t*);
```

**Comment by JohnoKing** [comment]
I've tested the patch and I haven't been able to break it so far. As far as the behavior with `return` in functions goes, it seems to most closely match `zsh` when testing it:
```sh
$ cat /tmp/foo
trap : EXIT
function foo { return -1; }
function bar { return 267; }
function normal { return 1; }
foo; echo $?
bar; echo $?
normal; echo $?
exit 0
$ arch/*/bin/ksh /tmp/foo  # ksh93u+m with patch applied
-1
267
1
$ zsh /tmp/foo
-1
267
1
$ ksh93u /tmp/foo  # ksh93u+ (ksh2020 behaves the same as 93u+)
255
267
1
$ bash /tmp/foo
255
11
1
$ mksh /tmp/foo
255
11
1
$ yash /tmp/foo
return: `-1' is not a valid option
2
267
1
```

**Comment by McDutchie** [comment]
Yes. You can use anything that fits into a 32-bit int, which I do think is like zsh.

I see no real reason not to allow it. Either we stick to the 8-bit limit as documented, which would make sense as it's consistent with `exit`, or we decide that that ship has sailed, but then we should just allow everything instead of being half-hearted about it. I'm tending towards the latter option now. It creates some interesting possibilities for scripts.

**Comment by McDutchie** [comment]
I found a subshell inconsistency ~~with the patch~~ (*edit:* actually this already existed in ksh 93u+ with the >256 return values it did allow):

```
$ arch/*/bin/ksh -c '(f() { return 12345; }; f); echo $?'                     
12345
$ arch/*/bin/ksh -c '(ulimit -t unlimited; f() { return 12345; }; f); echo $?'
57
```

The 8-bit exit status truncation of the forked subshell happens at the OS kernel level and we cannot control that. So, since non-forked subshells should be indistinguishable from real subshells, we'll have to truncate `sh.exitval` accordingly in sh_subshell() upon exiting a subshell.

```diff
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -871,6 +871,9 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 			srand(rp->rand_seed = sp->rand_seed);
 			rp->rand_last = sp->rand_last;
 		}
+		/* Real subshells have their exit status truncated to 8 bits by the kernel.
+		 * Since virtual subshells should be indistinguishable, do the same here. */
+		sh.exitval &= SH_EXITMASK;
 	}
 	shp->subshare = sp->subshare;
 	shp->subdup = sp->subdup;
```

**Comment by McDutchie** [comment]
In sh.funscope(), instead of:
```c
       if(sh.lastsig)
               kill(shgd->current_pid, sh.lastsig);
```
we should actually use:
```c
       if(jmpval==SH_JMPFUN && sh.lastsig)
               kill(shgd->current_pid, sh.lastsig);
```
as jmpval always has that value in the condition in which we need to do this. So the extra check seems safer. It's also exactly how sh_subshell() has been handling this for years: https://github.com/ksh93/ksh/blob/a874f8c16989079143ceeae52c2ba6ffde1ce3f8/src/cmd/ksh93/sh/subshell.c#L946-L947
