### ISSUE TITLE
memory leak with read -C when using <<<

### ISSUE THREAD

**Issue by dwierenga** [ksh93/ksh#369]
I'm not sure if this is a known issue or not, but I pulled the latest revision and compiled, and ran `bin/shtests`
I got this output:

```
test leaks(shcomp) begins at 2021-12-09+10:47:38
	shcomp-leaks.ksh[177]: memory leak with read -C when using <<< (leaked approx 256 KiB after 16384 iterations)
test leaks(shcomp) failed at 2021-12-09+10:48:12 with exit code 1 [ 41 tests 1 error ]
```

This is on a Macbook Pro running the M1 chip and Big Sur.

**Comment by McDutchie** [comment]
Thanks for the report. Did you try running the tests again to see if the failure repeats? I suspect this is one of those intermittent regression test failures and it's probably the result of OS memory management artefacts showing up through `ps`. If it keeps happening I'll have to increase the tolerance again. 256 KiB for 16384 iterations is a "leak" of 16 bytes per iteration which is quite small, though perhaps large enough to *possibly* represent a real leak. If it were a real memory leak it would also fail consistently instead of rarely and intermittently.

**Comment by McDutchie** [comment]
Meanwhile, on the assumption your failure is intermittent, I've added it to #344 and will close this as a separate issue. If you can reproduce it consistently, please do let me know, and I'll reopen it.

**Comment by McDutchie** [comment]
Hopefully this is now fixed as of https://github.com/ksh93/ksh/commit/d845675ced42dc60eb359cd1706e7542dbed6d30 and https://github.com/ksh93/ksh/commit/2569850f4a7caf1cd9464898cd6ff81251145530.

**Comment by dwierenga** [comment]
Looks good now, thanks!
