### ISSUE TITLE
Does anything described in sfdisc.3 exist?

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#426]
I cannot find any trace of the interfaces described in [src/lib/libast/man/sfdisc.3](https://github.com/ksh93/ksh/blob/d3fcbc75ea8afa687a01e15a094a4bb6255cfcba/src/lib/libast/man/sfdisc.3#L1). It states the lzw discipline is "not currently" distributed outside of AT&T due to patent concerns, but [the LZW patents expired in 2003 and 2004](https://groups.csail.mit.edu/mac/projects/lpf/Patents/Gif/Gif.html). But it seems *none* of this interface is present. Am I missing something? If not, we should simply remove this man page.

**Comment by JohnoKing** [comment]
I looked through all of ast-open-archive and I couldn't find a trace for the source code to these APIs anywhere. I've also done a [git blame](https://github.com/ksh93/ast-open-archive/blame/master/src/lib/libast/man/sfdisc.3) of the man page in question, and it hasn't received any significant updates since ksh93i.

**Comment by hyenias** [comment]
Perhaps this is it: src/lib/libpz/sfdczip.c

**Comment by McDutchie** [comment]
> Perhaps this is it: src/lib/libpz/sfdczip.c

Nice catch, but that looks more like a successor to the stuff described in sfdisc.3. See also [pzip.3](https://github.com/ksh93/ast-open-archive/blob/master/src/lib/libpz/pzip.3) under "SFIO DECOMPRESS DISCIPLINE".
