### ISSUE TITLE
Recursion error from `r` built-in

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#510]
@McDutchie Related to `r`, here's something odd (this is a freshly started shell):

```
$ r                                                                                                        
r
r
r
r
r
r
-ksh: hist: history: recursion too deep
$
```

I have no idea what caused it, and I can't make it happen again.  it's just weird.  The current history...

```
$ history
564	port contents ctags
565	port info universal-ctags
566	port info ctags
567	sudo port selfupdate
568	port outdated
569	sudo port upgrade -u outdated
570	sudo port upgrade -u outdated
571	cd ksh
572	git log | grep -i alias
573	m NEWS
574	/bin/ksh
575	ver
576	exit
577	unalias r
578	r
579	history
$
```

_Originally posted by @posguy99 in https://github.com/ksh93/ksh/discussions/503#discussioncomment-3337168_

**Comment by posguy99** [comment]
I figured out how to get the recursion error.

Start a new shell
```
$ unalias r
$ r
-ksh: r: not found
$ 
```

Kill that shell, start a new one with the same history file.

`$ r
`

And you get the recursion error.

**Comment by McDutchie** [comment]
I can only reproduce this if I launch the ksh shells from a shell other than ksh, which makes sense, as 'r' needs to be the last command in the history.

I'm going to go with 'not a bug' for this one. You've deliberately created a situation where the `r` alias recursively invokes `r`, and ksh happily obliges. It even fails gracefully by detecting excessive recursion instead of crashing. So I don't see a problem here.

**Comment by posguy99** [comment]
Agreed.

I can get u+ to do it as well.  Sometimes you really wish `ksh` had HISTIGNORE. 🤷‍♂️

**Comment by posguy99** [comment]
NOTABUG
