### ISSUE TITLE
Intermittent incorrect output of `.sh.match`

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#577]
### Discussed in https://github.com/ksh93/ksh/discussions/576

<div type='discussions-op-text'>

<sup>Originally posted by **phidebian** November  6, 2022</sup>
I bumped into this and since I am 're-learning' ksh from scratch, I feel a bit disorientated, so pardon if there is a trivial answer to this.

```
PW$ /d1/ksh-latest/arch/gnu.i386-64/bin/ksh  --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+f215b10a/MOD 2022-10-28
PW$ /d1/ksh-latest/arch/gnu.i386-64/bin/ksh -ci '[[ "[a] b [c] d" =~ ^\[[^]]+\] ]] && echo ${.sh.match}' 
[a]
logout
PW$ /d1/ksh-latest/arch/gnu.i386-64/bin/ksh -c '[[ "[a] b [c] d" =~ ^\[[^]]+\] ]] && echo ${.sh.match}' 
[a] b [c]
```
I learned that <code>=\~</code> is equivalent to <code>== \~(E)</code> but I see nothing in my installed man(1) (ubuntu 22.04, 93u+m/1.0.0-beta.2 2021-12-17) that add a interactive condition to the <code>=\~</code> form.

It looks like for interactive <code>=\~</code> is equivalent to <code>== \~(-E)</code> while for non interactive seems that <code>=\~</code> is equivalent to <code>== \~(E)</code> (as documented)

So the <code>=\~</code> greed seems to be different for interactive vs non-interactive, yet if using something else for <code>\[ or \] for instance :</code> then <code>\~(E)</code> is always non greedy.

And indeed the <code>~(E)ere </code> with ? to control the greed is working, so I guess <code>\~(E)</code> should always be greedy and the greed be controlled with ?

```
PW$ /d1/ksh-latest/arch/gnu.i386-64/bin/ksh -c '[[ "[a] b [c] d" =~ ^\[[^]]+?\] ]] && echo ${.sh.match}' 
[a]

```

Well I don't know what is normal or not for ksh93 but the variable behavior for interactive vs non-interactive is disturbing to (not orthogonal) to me.

Any helps appreciated.
</div>

**Comment by phidebian** [comment]
May be a reproduction problems can be introduced if we omit the echo quoting. May be you may update the reprod case as <code>echo "..."</code>
```
ksh -i -c '[[ "[a] b [c] d" =~ ^\[[^]]+\] ]] && echo "${.sh.match}"' 
[a] b [c]
```
Should produce <code>[a]</code>

**Comment by McDutchie** [comment]
When we use something else than literal brackets, like `X` and `Y`, or even literal parentheses, it works correctly:

```
$ [[ "XaY b XcY d" =~ ^X[^Y]+Y ]] && echo "${.sh.match}"  
XaY
$ [[ "(a) b (c) d" =~ ^\([^)]+\) ]] && echo "${.sh.match}"
(a)
```

**Comment by phidebian** [comment]
@McDutchie I received a gmail notification of your reply above, but I don't know if replying by gmail is a good idea (not sure it makes its way back here I am not poficient in github), then I reply here.

Yes, in the explanation in the discussion I said using something else 'work'.

Now I think I got the big picture, and as I feared, I will not be able to decide which path to follow to fix it, there are 2 ways of seeing this, and I am afraid the majority will want the wrong one, yet I can fix it for both ways, you (or guru's) will just have to tell me what path you prefere.

What was called wrong initially was right in my opinion, but other may say otherwise.

The correct is to match the longuest string here <code>[a] b [c] d</code> should match <code>[a] b [c]</code> because ksh (and bash) claim that <code>=~ </code> recognise ERE given by regex(7) which says that it got to grab the longest match. At fist I thought it was wrong because I was polluted by decade of bash/perl programing, then lost sight of original programing. And then as given in most moderne ERE doc's we can choose the shortest match with <code>^\[[^]]+?\]</code>  (note the ?) and ksh implement this just fine.

So basically the interactive is wrong as it always give the shortest match.

Now, other may say, ok, but the 'interactive' always provide the shortest match like bash, and we should not break that, ok but then we have no way to explicitly say we want the longest match, even though ksh93 proviosioned for it (see later), so we could use  that later if we really want to allow longuest match.

The catch of the '?' in the <code>^\[[^]]+?\]</code> is there

```
regcomp.c::1840

		switch (token(env))
		{
		case T_QUES: <======= The ? catching and processing
			eat(env);
			minimal = !(env->flags & REG_MINIMAL);
			break;
		case T_STAR: /*AST*/  <======= The * catching and processing that we may use in fix#2
			eat(env);
			minimal = !!(env->flags & REG_MINIMAL);
			break;
```


The interactive vs non interactive is a fake reason (as you feared due to your difficulties to reproduce), my interactive setup end up with <code>LC_ALL=C</code> (.kshrc) while my non interactive runs endup with <code)LC_ALL=C.UTF-8</code>. That's big of a deal because regexec has 2 path depending on the fact we are mono byte per char vs multi-byte per char (wchar).

1. The mono byte per char (char)
```
regnexec.c::894
		case REX_CLASS:
			if (LEADING(env, rex, s))
				return NONE;
			n = rex->hi;
			if (n > env->end - s)
				n = env->end - s;
			m = rex->lo;
			if (m > n)
				return NONE;
			r = NONE;
			if (!(rex->flags & REG_MINIMAL))
			{
				for (i = 0; i < n; i++)
					if (!settst(rex->re.charclass, s[i]))
					{
						n = i;
						break;
					}
				for (s += n; n-- >= m; s--)
```
2. The multi byte (wchar) code, this one is interesting because first of all it is correct, and then it as 2 case the 'minimal' case (shortest match) and the non-minimal (longest match), something the mono byte code miss, only implement the wrong shortest match.
```
regnexec.c::950
		case REX_COLL_CLASS:
			if (LEADING(env, rex, s))
				return NONE;
			n = rex->hi;
			if (n > env->end - s)
				n = env->end - s;
			m = rex->lo;
			if (m > n)
				return NONE;
			r = NONE;
			e = env->end;
			if (!(rex->flags & REG_MINIMAL)) <------- longest match
			{ 
                         . . .
           		else <---------------------------------------------- shortest match
			{
				for (i = 0; i < m && s < e; i++, s = t)
					if (!collmatch(rex, s, e, &t))
						return r;
				while (i++ <= n)
				{
					switch (follow(env, rex, cont, s))
					{
					case BAD:
						return BAD;
					case CUT:
						return CUT;
					case BEST:
					case GOOD:
						return BEST;
					}
					if (s >= e || !collmatch(rex, s, e, &s))
						break;
				}

```
Now the fixes, if the 'majority' want the bash behavior, and the ksh LC_ALL=C behavior then the regcomp.c  should add the REG_MINIMAL flag for that 're' or 'env'.
```
regcomp.c::2196
			case 'E':
				env->flags &= ~(REG_AUGMENTED|REG_EXTENDED|REG_LITERAL|REG_REGEXP|REG_SHELL|REG_LEFT|REG_RIGHT);
				env->flags |= REG_EXTENDED;  <<---- Should add REG_MINIMAL
				typ = ERE;
				break;
```
With this we will work as bad as bash.... and have no more chance to request a longest match, unless we implement the second fix that would be to use the <code>T_STAR: /*AST*/ </code> se earlier, but then this T_STAR should be implement in the mono byte per char too,  well this is the last point I didn't reviewed right now, may be the fix would be minimal, yet I fear we will not go this way, so there is no real need to investigate more on that for now.

If you tell me which path to go I can cut a patch for you.

Cheer.
PS: If one know how to 'highlight' piece of code, I 'd be happy to knw, because for now I do <<---- kind of headsup that is hugly. Thax in advance.

**Comment by phidebian** [comment]
Just made a quick test and the QA break big time so my code review is partial I guess but I guess to problem is in the vicinity... I'll try harder tomorow...

**Comment by phidebian** [comment]
I submitted a PR candidate. 
The fix implement the shortest match behavior (common with bash, and ksh93 with LC_ALL=C.
Not sure this is the regex(7) spirit, though I don't really understand the regex(7) wording regarding greed, but it seems the best thing to do. You will decide.

**Comment by McDutchie** [comment]
Thanks. That would be #581. Let's try it. (Sorry for delay.)
