### ISSUE TITLE
typeset -f is printing too much

### ISSUE THREAD

**Issue by hckiang** [ksh93/ksh#589]
When a function definition doesn't end with `;` typeset -f will give strange output:
```{sh}
$ test T = T && fun() { echo 'HELLO'; } || fun () { echo 'WORLD'; }                                     
$ typeset -f fun
fun() { echo 'HELLO'; } ||$
```

Compare what is "normal" if we wrap the definition in a `{}` block:
```{sh}
$ test T = T && { fun() { echo 'HELLO'; }; } || fun () { echo 'WORLD'; }
$ typeset -f fun                                                        
fun() { echo 'HELLO'; };$
```

**Comment by McDutchie** [comment]
Thanks for the report.

This is another artefact of the way the 93u+ (and the 93u+m/1.0 series) print function definitions. When defining a function, ksh remembers the offset and length of the function in the original file – in your example from an interactive shell, that original file is the command history file, `~/.sh_history`. So `typeset -f` simply dumps the original function definition text from the history file.

The bug you've observed is not the only problem with that. As soon as your history file is removed or overwritten, the output of `typeset -f` will be corrupted altogether.

It is the same with function definitions loaded from files, e.g. with `.`/`source` or via autoload. `typeset -f` works fine as long as the original file is unchanged. But as soon as you edit it in a way that invalidates the offset and/or length of the function definition, `typeset -f` output is corrupted.

I've concluded this is not a sane way of doing it, and instead of fixing it, this mechanism needs to be replaced entirely.

In the future 93u+m/1.1 series (currently being developed on the dev branch) I've begun that process. We'll be using the previously disused deparse.c module from 93u+m for that. It regenerates shell script from the internal binary representation. This is also how `typeset -f` operates on bash, mksh and zsh. See f21ace5cde9b9e91fb93b2b95f9978169f798d9a.

So, on a ksh compiled from the current dev branch, the output of your reproducer is:

```
$ test T = T && fun() { echo 'HELLO'; } || fun () { echo 'WORLD'; }                                                                  
$ typeset -f fun
fun()
{	echo HELLO
}
$ 
```

Unfortunately I've been finding serious bugs in deparse.c because it was unused for so long, so we'll have to fix those before releasing 1.1.0. #530 is one of those.

But this does mean I will not be spending any effort on fixing bugs in the old mechanism. It is fundamentally unfixable, because it assumes the source file never changes, which is an invalid assumption. So I'm afraid the 93u+m/1.0.x behaviour is what it is.
