### ISSUE TITLE
Array slicing incorrect result

### ISSUE THREAD

**Issue by husixu1** [ksh93/ksh#605]
This
```ksh
a=(1 2 3); len=${#a[@]}; echo "${a[*]:0:$len}";
```
prints `1 2 3`. But this
```ksh
a=(1 2 3); echo "${a[*]:0:${#a[@]}}";
```
prints `1 1 2`.

Testing envivonment: 
```ksh
$ ksh --version
  version         sh (AT&T Research) 93u+m/1.1.0-alpha+a86a7c0b/MOD 2023-03-04
```

**Comment by McDutchie** [comment]
Thanks for the report. My testing with old ksh versions compiled from the [ksh93-history repo](/ksh93/ksh93-history) shows that this bug was introduced between 2008-02-02 and 2008-06-02 as the latter is the earliest version in that repo with the bug. Unfortunately no other versions within that four month time span are available and quite a lot changed, so it'll be non-trivial to pinpoint the change that introduced the bug.

**Comment by McDutchie** [comment]
[This](https://github.com/ksh93/ksh93-history/blob/4045ebcf66e758bfe55ac273299e3c09238d6387/src/cmd/ksh93/sh/macro.c#L1332-L1444) is the 2008-02-02 code for `${name:expr1[:expr2]}` and [this](https://github.com/ksh93/ksh93-history/blob/6a8dad6ce3bf3ae2365265344fa05bbbea4ab55f/src/cmd/ksh93/sh/macro.c#L1447-L1559) is the 2008-06-02 code for same. Apart from general internal API changes (introducing pointers to sh), it's identical. So that doesn't help.

**Comment by McDutchie** [comment]
I tried backporting the 2008-02-02 version of `varsub()` to 93u+m; this bug disappeared, so the bug must be somewhere in that huge `varsub()` function.

Using systematic elimination of those changes I found the line that introduced the bug. It is the addition of ` && type!=M_SIZE)` on line 1426 that introduced it. Undoing that using the following patch makes the bug go away:

```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 84570a73e..40ef2eea4 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1423,7 +1423,7 @@ retry1:
 						np = 0;
 				}
 			}
-			else if(ap && (isastchar(mode)||type==M_TREE)  && !(ap->nelem&ARRAY_SCAN) && type!=M_SIZE)
+			else if(ap && (isastchar(mode)||type==M_TREE)  && !(ap->nelem&ARRAY_SCAN))
 				nv_putsub(np,NIL(char*),ARRAY_SCAN);
 			if(!isbracechar(c))
 				goto nosub;
```

Unfortunately the patch cannot be applied as is, because it causes a couple of regression test failures:

```
	cubetype.sh[80]: FAIL: ${#bb.colors[@]} incorrect for iteration 0 -- expected 2, got '3'
	cubetype.sh[80]: FAIL: ${#bb.colors[@]} incorrect for iteration 1 -- expected 2, got '3'
```

**Comment by McDutchie** [comment]
Those regression tests involve associative arrays. If we add an exclusion of associative arrays, then the bug disappears without causing any regression test failures. I'm not fully confident that this is correct because I still don't fully understand that massive, barely commented varsub() function, but the following patch does seem to work:
```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 84570a73e..a6bae6226 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1423,7 +1423,7 @@ retry1:
 						np = 0;
 				}
 			}
-			else if(ap && (isastchar(mode)||type==M_TREE)  && !(ap->nelem&ARRAY_SCAN) && type!=M_SIZE)
+			else if(ap && (isastchar(mode)||type==M_TREE) && !(ap->nelem&ARRAY_SCAN) && !(type==M_SIZE && array_assoc(ap)))
 				nv_putsub(np,NIL(char*),ARRAY_SCAN);
 			if(!isbracechar(c))
 				goto nosub;
```

**Comment by McDutchie** [comment]
So the bug is that `nv_putsub(np,NIL(char*),ARRAY_SCAN);` doesn't get called when it should. It sets the array index to start scanning at, the null pointer argument signifying the first available element (see `man src/cmd/ksh93/nval.3`).

It doesn't make a lot of sense to call `nv_putsub` when expanding the inner `${#`*name*`}`, because the `nv_putsub` call is actually for the outer `${`*name*`:`*index*`:`*length*`}` to work properly.

The following patch to the `${`*name*`:`*index*`:`*length*`}` code fixes the issue as well (apply **instead** of the previous one) and I have more confidence in it, as it addresses the cause directly: the bug only occurs if the *index* is 0. In this context, `type` is the value of the *index* (this code is so old it's still re-using variables as a performance/memory optimisation; I might fix that separately at some point):

```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 84570a73e..5bf60d4ad 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1755,7 +1755,7 @@ retry1:
 					while(type-- >0 && (v=0,nv_nextsub(np)))
 						v = nv_getval(np);
 				}
-				else if(type > 0)
+				else if(type >= 0)
 				{
 					if(nv_putsub(np,NIL(char*),type|ARRAY_SCAN))
 						v = nv_getval(np);
```

**Comment by McDutchie** [comment]
Now that I understand the cause of the bug, I can figure out some other reproducers. Here's one:

Before:
```
$ a=(1 2 3 4 5); echo "${a[*]:0:${a[@]:3:1}}"
1 1 2 3
```

After:

```
$ arch/*/bin/ksh -c 'a=(1 2 3 4 5); echo "${a[*]:0:${a[@]:3:1}}"'
1 2 3 4
```

**Comment by hyenias** [comment]
Nice work. This issue seems similar to my fix for arithmetic assignment expressions for indexed multidimensional arrays. The trouble with it was that even though ksh was keeping track of the sub (index/offset) it did not keep track of the associated array for that sub/index, so when putsub was called it defaulted to the top most parent array.

I hand tested this fix for about 30 mins or so and found no issues with one dimensional indexed arrays. However, when tested with multidimensional arrays incorrect behavior occurs which is more than likely due to not keeping track of the associated name pointer to the particular array for that sub number.

```ksh
$ ksh605 +E -c 'arr=(a (b d e) c); echo ${arr[@]}'
a b c
$ ksh605 +E -c 'arr=(a (b d e) c); echo ${arr[@]:}'
a b c
$ ksh605 +E -c 'arr=(a (b d e) c); echo ${arr[@]:0}'
a b c
$ ksh605 +E -c 'arr=(a (b d e) c); echo ${arr[@]:0:${#arr[@]}}'
a a
$ ksh605 +E -c 'arr=(a b (c d e)); echo ${arr[@]:0:${#arr[@]}}'
a a
$ ksh605 +E -c 'arr=((a d e) b c); echo ${arr[@]:0:${#arr[@]}}'
a b c
```

**Comment by McDutchie** [comment]
Thanks for testing that, @hyenias. I'm going to be travelling for a few days, perhaps you could fix this properly in the meantime? :)

**Comment by hyenias** [comment]
More insights into the particular trouble. It appears that only when self-referencing does the trouble occur. So, more than likely not keeping proper track of the correct sub and/or np. When one uses a different variable to obtain the length the issue is avoided. Perhaps it could be as simple of not resetting some variable. As you pointed out, perhaps too much variable reuse.

```
# 1 ---
$ ksh +E -c 'arr=(a (b d e) c); echo ${arr[@]:0:${#arr[@]}}'
a a
$ ksh +E -c 'i=(1 2 3); arr=(a (b d e) c); echo ${arr[@]:0:${#i[@]}}'
a b c

# 2 ---
$ ksh +E -c 'i=(1 2 3); arr=(1 2 3); echo ${arr[@]:0:${#arr[@]}}';
1 1 2
$ ksh +E -c 'i=(1 2 3); arr=(1 2 3); echo ${arr[@]:0:${#i[@]}}';
1 2 3

# 3 ---
$ ksh +E -c 'i=(1 2 3 4); arr=(1 2 3 4 5); echo ${arr[@]:0:${arr[@]:3:1}}'
1 1 2 3
$ ksh +E -c 'i=(1 2 3 4); arr=(1 2 3 4 5); echo ${arr[@]:0:${i[@]:3:1}}'
1 2 3 4

# 4 --- All work. Just testing the use of a non $ variable lookup in the expressions
$ ksh +E -c 'len=3; arr=(1 2 3 4 5); echo ${arr[@]:0:len}'
1 2 3
$ ksh +E -c 'i=(1 2 3 4); arr=(1 2 3 4 5); echo ${arr[@]:0:i[3]}'
1 2 3 4
```

**Comment by McDutchie** [comment]
> ```
> $ ksh +E -c 'len=3; arr=(1 2 3 4 5); echo ${arr[@]:0:len}'
> 1 2 3
> $ ksh +E -c 'i=(1 2 3 4); arr=(1 2 3 4 5); echo ${arr[@]:0:i[3]}'
> 1 2 3 4
> ```

That one does not show a bug; both commands are as expected. In the second one, i[3]==4 (since array indexes start at 0), so `1 2 3 4` is the expected output.

**Comment by McDutchie** [comment]
Your second and third sets of reproducers seem to be fixed just by moving the second `sh_strnum` call forward (which also requires eliminating the reuse of `type`), as in the patch below. The first one still remains buggy though.
<details>
<summary>Test patch</summary>

```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 84570a73e..4a2557de7 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1718,52 +1718,56 @@ retry1:
 	if(c==':')  /* ${name:expr1[:expr2]} */
 	{
 		char *ptr;
-		type = (int)sh_strnum(argp,&ptr,1);
+		int expr1, expr2;
+		char expr2set;
+		expr1 = (int)sh_strnum(argp,&ptr,1);
+		if(expr2set = (*ptr == ':'))
+			expr2 = (int)sh_strnum(ptr+1,&ptr,1);
 		if(isastchar(mode))
 		{
 			if(id==idbuff)  /* ${@} or ${*} */
 			{
-				if(type<0 && (type+= dolmax)<0)
-					type = 0;
-				if(type==0)
+				if(expr1<0 && (expr1+= dolmax)<0)
+					expr1 = 0;
+				if(expr1==0)
 					v = special(dolg=0);
 #if  SHOPT_FILESCAN
 				else if(sh.cur_line)
 				{
-					v = getdolarg(dolg=type,&vsize);
+					v = getdolarg(dolg=expr1,&vsize);
 					if(!v)
-						dolmax = type;
+						dolmax = expr1;
 				}
 #endif  /* SHOPT_FILESCAN */
-				else if(type < dolmax)
-					v = sh.st.dolv[dolg=type];
+				else if(expr1 < dolmax)
+					v = sh.st.dolv[dolg=expr1];
 				else
 					v =  0;
 			}
 			else if(ap)
 			{
 				ap = nv_arrayptr(np); /* update */
-				if(type<0)
+				if(expr1<0)
 				{
 					if(array_assoc(ap))
-						type = -type;
+						expr1 = -expr1;
 					else
-						type += array_maxindex(np);
+						expr1 += array_maxindex(np);
 				}
 				if(array_assoc(ap))
 				{
-					while(type-- >0 && (v=0,nv_nextsub(np)))
+					while(expr1-- >0 && (v=0,nv_nextsub(np)))
 						v = nv_getval(np);
 				}
-				else if(type > 0)
+				else if(expr1 >= 0)
 				{
-					if(nv_putsub(np,NIL(char*),type|ARRAY_SCAN))
+					if(nv_putsub(np,NIL(char*),expr1|ARRAY_SCAN))
 						v = nv_getval(np);
 					else
 						v = 0;
 				}
 			}
-			else if(type>0)
+			else if(expr1>0)
 				v = 0;
 			if(!v)
 				mp->atmode = 0;
@@ -1771,24 +1775,24 @@ retry1:
 		else if(v)
 		{
 			vsize = charlen(v,vsize);
-			if(type<0 && (type += vsize)<0)
-				type = 0;
-			if(vsize < type)
+			if(expr1<0 && (expr1 += vsize)<0)
+				expr1 = 0;
+			if(vsize < expr1)
 				v = 0;
 			else if(mbwide())
 			{
 				mbinit();
-				for(c=type;c;c--)
+				for(c=expr1;c;c--)
 					mbchar(v);
 				c = ':';
 			}
 			else
-				v += type;
+				v += expr1;
 			vsize = v?strlen(v):0;
 		}
-		if(*ptr==':')
+		if(expr2set)
 		{
-			if((type = (int)sh_strnum(ptr+1,&ptr,1)) <=0)
+			if(expr2 <= 0)
 			{
 				v = 0;
 				mp->atmode = 0;
@@ -1797,28 +1801,28 @@ retry1:
 			{
 				if(dolg>=0)
 				{
-					if(dolg+type < dolmax)
-						dolmax = dolg+type;
+					if(dolg+expr2 < dolmax)
+						dolmax = dolg+expr2;
 				}
 				else
-					dolmax = type;
+					dolmax = expr2;
 			}
-			else if(type < vsize)
+			else if(expr2 < vsize)
 			{
 				if(mbwide())
 				{
 					char *vp = v;
 					mbinit();
-					while(type-->0)
+					while(expr2-->0)
 					{
 						if((c=mbsize(vp))<1)
 							c = 1;
 						vp += c;
 					}
-					type = vp-v;
+					expr2 = vp-v;
 					c = ':';
 				}
-				vsize = type;
+				vsize = expr2;
 			}
 			else
 				vsize = v?strlen(v):0;
```
</details>

**Comment by McDutchie** [comment]
> ```
> $ ksh +E -c 'arr=(a (b d e) c); echo ${arr[@]:0:${#arr[@]}}'
> a a
> ```

This fails (even with the above patch) because `arr` is interpreted as an associative array (`array_assoc(ap)` yields true). For an associative array, the slicing operation is meaningless (I think).

```
$ ksh +E -c 'arr=(a (b d e) c); typeset -p arr; ; echo ${arr[@]:0:${#arr[@]}}'
typeset -A arr=([0]=a [1]=(b d e) [2]=c)
a a
```

If we explicitly declare an indexed array, it works fine after applying the above patch:

```
$ arch/darwin.arm64-64/bin/ksh +E -c 'typeset -a arr=(a (b d e) c); typeset -p arr; echo ${arr[@]:0:${#arr[@]}}'
typeset -a arr=(a (b d e) c)
a b c
```

So perhaps it is a (separate) bug that `arr` is implicitly defined as an associative array when `typeset` is not used. This does not make sense to me in any case. What do you think, @hyenias?

**Comment by hyenias** [comment]
@McDutchie, you are 100% correct that using a compound assignment statement was ambiguous to ksh93 and possibly a bug; see #148. Good catch and my mistake for not explicitly declaring an indexed array. I was caught up with my hand testing and did not notice it.

So, with your latest patch this issue seems to be resolved. I will hand test again soon using your test patch above.

**Comment by hyenias** [comment]
> For an associative array, the slicing operation is meaningless (I think).

The index slicing of the array's elements returns each element's 1st value. It all works similarly except when using self referencing parameter expansion with associative arrays, examples: `${arr[@]:${#arr[@]}-1}, ${arr[@]:${arr[a]}}, ${arr[@]:0:${#arr[@]}}`. When the array is an associative array and referring to itself, then odd things happen. This is a corner case.

So, as it stands with your patch and existing ksh; if using associative arrays and one wishes to calculate/manipulate the index or length expression of a slice/substring then one needs to use a separate variable to do so. This is not a big deal to me as most folks wanting to return the entire array should simply just call `${arr[@]}` which does the same thing as `${arr[@]:}` or `${arr[@]:0:${#arr[@]}` albeit faster. And as you mentioned, how much sense does it make skimming the top elements from an associative array? For me, if using associative arrays, I would code differently when iterating or listing out its values and would employ the use of other variables.

Everything works as expected with the caveat of not using self with associative arrays in parameter expansions.

**Comment by McDutchie** [comment]
Regardless of whether a slicing operation on an associative array is meaningful or not, as long as

```sh
typeset -A arr=(a (b d e) c)
num=${#arr[@]}
echo ${arr[@]:0:num}
```

and

```sh
typeset -A arr=(a (b d e) c)
echo ${arr[@]:0:${#arr[@]}}
```

don't produce identical results, there is still a bug and I'm not happy.

**Comment by McDutchie** [comment]
That probably shouldn't block the resolution of this issue though as it's probably a separate bug.

**Comment by McDutchie** [comment]
I think I found the fix for the remaining associative array bug. There is explicit code for associative array slicing, so it's not a meaningless operation.

But there's a missing nv_putsub() call in that code (on line 1760 as of the patch below), which is needed to reset the array scan state in case a recursive expansion was done. To avoid breakage with a multidimensional array, the `ARRAY_SCAN` flag must only be passed if that flag wasn't already set, hence:

```c
nv_putsub(np, NIL(char*), ap->nelem&ARRAY_SCAN ? 0 : ARRAY_SCAN);
```

All your reproducers are working for me now.

<details>
<summary>New patch</summary>

```diff
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 84570a73e..1271bfbda 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1717,53 +1717,59 @@ retry1:
 	}
 	if(c==':')  /* ${name:expr1[:expr2]} */
 	{
-		char *ptr;
-		type = (int)sh_strnum(argp,&ptr,1);
+		int e1, e2;
+		char e2set, *ptr;
+		e1 = (int)sh_strnum(argp,&ptr,1);
+		if(e2set = (*ptr == ':'))
+			e2 = (int)sh_strnum(ptr+1,&ptr,1);
+		if(*ptr)
+			mac_error();
 		if(isastchar(mode))
 		{
 			if(id==idbuff)  /* ${@} or ${*} */
 			{
-				if(type<0 && (type+= dolmax)<0)
-					type = 0;
-				if(type==0)
+				if(e1<0 && (e1+= dolmax)<0)
+					e1 = 0;
+				if(e1==0)
 					v = special(dolg=0);
 #if  SHOPT_FILESCAN
 				else if(sh.cur_line)
 				{
-					v = getdolarg(dolg=type,&vsize);
+					v = getdolarg(dolg=e1,&vsize);
 					if(!v)
-						dolmax = type;
+						dolmax = e1;
 				}
 #endif  /* SHOPT_FILESCAN */
-				else if(type < dolmax)
-					v = sh.st.dolv[dolg=type];
+				else if(e1 < dolmax)
+					v = sh.st.dolv[dolg=e1];
 				else
 					v =  0;
 			}
 			else if(ap)
 			{
 				ap = nv_arrayptr(np); /* update */
-				if(type<0)
+				if(e1<0)
 				{
 					if(array_assoc(ap))
-						type = -type;
+						e1 = -e1;
 					else
-						type += array_maxindex(np);
+						e1 += array_maxindex(np);
 				}
 				if(array_assoc(ap))
 				{
-					while(type-- >0 && (v=0,nv_nextsub(np)))
+					nv_putsub(np, NIL(char*), ap->nelem&ARRAY_SCAN ? 0 : ARRAY_SCAN);
+					while(e1-- >0 && (v=0,nv_nextsub(np)))
 						v = nv_getval(np);
 				}
-				else if(type > 0)
+				else if(e1 >= 0)
 				{
-					if(nv_putsub(np,NIL(char*),type|ARRAY_SCAN))
+					if(nv_putsub(np,NIL(char*),e1|ARRAY_SCAN))
 						v = nv_getval(np);
 					else
 						v = 0;
 				}
 			}
-			else if(type>0)
+			else if(e1>0)
 				v = 0;
 			if(!v)
 				mp->atmode = 0;
@@ -1771,24 +1777,24 @@ retry1:
 		else if(v)
 		{
 			vsize = charlen(v,vsize);
-			if(type<0 && (type += vsize)<0)
-				type = 0;
-			if(vsize < type)
+			if(e1<0 && (e1 += vsize)<0)
+				e1 = 0;
+			if(vsize < e1)
 				v = 0;
 			else if(mbwide())
 			{
 				mbinit();
-				for(c=type;c;c--)
+				for(c=e1;c;c--)
 					mbchar(v);
 				c = ':';
 			}
 			else
-				v += type;
+				v += e1;
 			vsize = v?strlen(v):0;
 		}
-		if(*ptr==':')
+		if(e2set)
 		{
-			if((type = (int)sh_strnum(ptr+1,&ptr,1)) <=0)
+			if(e2 <= 0)
 			{
 				v = 0;
 				mp->atmode = 0;
@@ -1797,34 +1803,32 @@ retry1:
 			{
 				if(dolg>=0)
 				{
-					if(dolg+type < dolmax)
-						dolmax = dolg+type;
+					if(dolg+e2 < dolmax)
+						dolmax = dolg+e2;
 				}
 				else
-					dolmax = type;
+					dolmax = e2;
 			}
-			else if(type < vsize)
+			else if(e2 < vsize)
 			{
 				if(mbwide())
 				{
 					char *vp = v;
 					mbinit();
-					while(type-->0)
+					while(e2-->0)
 					{
 						if((c=mbsize(vp))<1)
 							c = 1;
 						vp += c;
 					}
-					type = vp-v;
+					e2 = vp-v;
 					c = ':';
 				}
-				vsize = type;
+				vsize = e2;
 			}
 			else
 				vsize = v?strlen(v):0;
 		}
-		if(*ptr)
-			mac_error();
 		stkseek(stkp,offset);
 		argp = 0;
 	}
```
</details>
