### ISSUE TITLE
The exit status of command terminated with a signal in the pipeline seems be wrong

### ISSUE THREAD

**Issue by ko1nksm** [ksh93/ksh#742]
The `seq` command seems to terminate with `256+signum` (unlike `128+signum` in other shells) as expected, but the shell does not seem to get the values right. Perhaps it has something to do with the exit status value obtained from the subshell, but I don't know what is right.

**ksh93u+m/1.1.0-alpha+8f84f4b2**

```console
$ ksh -c 'set -o pipefail; (seq 1000000; xs=$?; echo $xs >&2; exit $xs) | head > /dev/null; echo $?'
269
13

$ ksh -c '(exit 255); echo $?; (exit 256); echo $?; (exit 257); echo $?'
255
0
1

$ ksh -c 'set -o pipefail; (exit 255)|:; echo $?; (exit 256)|:; echo $?; (exit 257)|:; echo $?'
255
0
1
```

**ksh93u+**

```console
$ ksh -c 'set -o pipefail; (seq 1000000; xs=$?; echo $xs >&2; exit $xs) | head > /dev/null; echo $?'
269
141

$ ksh -c '(exit 255); echo $?; (exit 256); echo $?; (exit 257); echo $?'
255
0
257

$ ksh -c 'set -o pipefail; (exit 255)|:; echo $?; (exit 256)|:; echo $?; (exit 257)|:; echo $?'
255
0
129
```

**Comment by McDutchie** [comment]
ksh 93u+m works as expected here. The 93u+ behaviour is buggy and has been fixed.

When a subshell exits, the exit status (`$?`) is trimmed to its least significant 8 bits. For a separate process (such as a real subshell) this is enforced by the kernel. So a virtual subshell should act the same, because its operation should be indistinguishable from a real subshell. See b90b8cd59f.

The exception is if a subshell, or the last command it ran, was terminated by a signal. The signal is then reissued to the parent environment and you get an exit status > 256. But that is not the case in your examples, because your subshells all exit normally with the `exit` command.

I hope this clarifies.
