### ISSUE TITLE
Single-character long option oddity

### ISSUE THREAD

**Issue by dnewhall** [ksh93/ksh#795]
When you specify long options for an option in getopts, `--<original-character>` will also work as an argument. So, for the optstring `"v(verbose)"`, `-v` works, `--verbose` works, but also `--v`.

If you specify a long option of just one character, that will also always work. So, for `"v(verbose)(V)"`, `-v` works, `--verbose` works, `--v` works, as well as `--V` (but `-V` will not).

**UNLESS** the single-character long option is the only long option provided:
```shell
optstring="v(V)"
while getopts ":$optstring" opt
do
   print -- "$opt"
done
```
Now, for the above, `-v` works as expected, `--V` works as expected, but `--v` no longer works.

(Version is 93u+m/1.0.10 2024-08-01 on Linux x64)

**Comment by McDutchie** [comment]
This is a known feature. Long options can be abbreviated until the point where the abbreviation would match multiple options, making them ambiguous. This is a feature of optget(3) in libast, so all ksh commands with long options support it.

For example, `typeset --v` is the same as `typeset --version` because there are no other long options starting with `v`. But for the built-in `cp` (which is on the virtual `/opt/ast/bin` path), there are both `--version` and `--verbose`, so the shortest possible abbreviations are `--vers` and `--verb`.

**Comment by dnewhall** [comment]
Ah, OK. I never knew it was doing smart/partial matching on the long option. I always thought it was just adding "--v" because that was the name of the short option. Thanks!
