### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by posguy99** [ksh93/ksh#81]
It's not "broken", but what is the standard for ksh93/ksh?

```
[10:04 AM][ttys000][~/src/ksh]
[245] mbp13 $ /usr/local/bin/ksh --version
  version         sh (AT&T Research) 93u+m 2020-07-16
[10:05 AM][ttys000][~/src/ksh]
[246] mbp13 $ echo $KSH_VERSION           
Version AJM 93u+m 2020-07-16
[10:05 AM][ttys000][~/src/ksh]
[247] mbp13 $ git log                     

commit 36f55f1f857f84c3ca88664b8050853e15350ade (HEAD -> master, origin/master, origin/HEAD)
Author: Martijn Dekker <martijn@inlv.org>
Date:   Sun Jul 19 06:42:53 2020 +0100

```

Huh?

**Comment by McDutchie** [comment]
I see nothing wrong there. Could you clarify what your question is?

**Comment by posguy99** [comment]
The binary is calling itself version "2020-07-16", but the latest commit is dated 2020-07-19.  I built that binary from HEAD.  I think I'm fishing for what causes the version string to be updated.  Besides the obvious that someone commits a patch changing it, of course.

**Comment by JohnoKing** [comment]
The version string currently has to be updated manually (the date doesn't change automatically):
https://github.com/ksh93/ksh/blob/36f55f1f857f84c3ca88664b8050853e15350ade/src/cmd/ksh93/include/version.h#L20

**Comment by McDutchie** [comment]
The version string lives in `src/cmd/ksh93/include/version.h` and gets updated as part of a commit, just like every other file. This should be done for every commit that adds a `NEWS` entry, although sometimes it gets forgotten.

**Comment by McDutchie** [comment]
Another thing that may not be commonly known: the `AJM` letters in the `${sh.version}` expansion indicate features that the shell was compiled with; they may change as `SHOPT_*` options are disabled or enabled during compilation. These are added using preprocessor directives, here:
https://github.com/ksh93/ksh/blob/36f55f1f857f84c3ca88664b8050853e15350ade/src/cmd/ksh93/sh/init.c#L85-L117

**Comment by posguy99** [comment]
Yup.  I'd gone through the source file and found out what the feature codes meant.  What tripped me up was that I was *sure* I'd built a new binary that had the -Os change, but the date didn't change.  Since I'm updating ksh on two different Mac, I got truly confused.  I'm going to stop keeping two separate clones of the repo.

**Comment by McDutchie** [comment]
On the Mac, `-Os` was already a default flag, added a hack in `src/cmd/INIT/cc.darwin` because that's what Apple did for its stock /bin/ksh. It was hackish because the compiler command showed `-O` but it was really compiled with `-Os`.  (It also made it impossible to actually compile with `-O` by adding it to `CCFLAGS`.)

This is now [changed globally](https://github.com/ksh93/ksh/commit/37a9c34515c8c966447f75b10a5205934ca51d7d) in `src/cmd/INIT/make.probe` (note that this takes effect after deleting the `arch` directory and recompiling from scratch) and the Apple default flag hack has been [removed](https://github.com/ksh93/ksh/commit/5521c39a9bb856de8a413808dd2c764c9872b890).

But on the Mac you shouldn't see any difference in the binary if you compile using default flags.

**Comment by posguy99** [comment]
The binary shrank along the way, but it most likely was you removing the coshell stuff rather than the compiler flag.  I lost track.

**Comment by McDutchie** [comment]
Correct, removing the unused coshell library shrank it by about 43k.
